abstract final class AppRoutes {
  static const splash = '/';
  static const login = '/login';
  static const forgotPassword = '/login/forgot-password';
  static const register = '/register';
  static const projects = '/projects';
  static const joinProject = '/projects/join';
  static String projectMembers(String id) => '/projects/$id/members';
  static const dashboard = '/dashboard';
  static const orders = '/orders';
  static const newOrder = '/orders/new';
  static const incomingRebar = '/incoming-rebar';
  static const deliveryList = '/incoming-rebar/list';
  static const newDelivery = '/incoming-rebar/new';
  static const supplierPerformance = '/incoming-rebar/suppliers';
  static String deliveryDetail(String id) => '/incoming-rebar/$id';
  static const fieldCount = '/field-count';
  static const reconciliation = '/field-count/reconciliation';
  static const newCount = '/field-count/new';
  static String countDetail(String id) => '/field-count/$id';
  static const analysis = '/analysis';
  static const performanceAnalysis = '/analysis/performance';
  static const reports = '/reports';
  static String reportDetail(String id) => '/reports/$id';
  static const survey = '/survey';
  static const surveyMetraj = '/survey?tab=metraj';
  static String surveyDetail(String id) => '/survey/$id';
  static const settings = '/settings';
  static const companySettings = '/settings/company';
  static const projectSettings = '/settings/project';
  static const notificationSettings = '/settings/notifications';
  static const about = '/settings/about';
  static const emptyStates = '/settings/empty-states';
}
