/// Varsayılan meslek ve meslek grubu katalogları — santiye-takip ile aynı.
abstract final class ProfessionCatalog {
  static const List<String> defaultProfessions = [
    'Proje Koordinatörü',
    'Proje Müdürü',
    'Şantiye Şefi',
    'Saha Mühendisi',
    'Teknik Ofis Mühendisi',
    'Harita Mühendisi',
    'Jeoloji Mühendisi',
    'İSG Uzmanı',
    'Şenör',
    'Puantör',
    'Saha Formeni',
    'Makine Formeni',
    'Usta',
    'Ekskavatör Operatörü',
    'JCB Operatörü',
    'Kamyon Şoförü',
    'Kule Vinç Operatörü',
    'Mobil Vinç Operatörü',
    'Kantar Personeli',
    'Depo & Ambar Personeli',
    'Kalfa',
    'Kalfa Yardımcısı',
    'Saha Düz İşçi',
    'Gündüz Bekçisi',
    'Gece Bekçisi',
  ];

  static const List<String> defaultTradeGroups = [
    'Hafriyat',
    'Kaba İnşaat',
    'Kalıp',
    'Demir',
    'Beton',
    'Duvar',
    'Çelik',
    'Sıva',
    'Şap',
    'İzolasyon',
    'Çatı',
    'Seramik / Fayans',
    'Boya',
    'Alçı Sıva',
    'Asma Tavan',
    'Alüminyum / Doğrama',
    'Su Tesisatı',
    'Elektrik',
    'Mekanik / Havalandırma',
    'Yangın Tesisatı',
    'Peyzaj',
    'Genel',
  ];
}
