import { AssetType } from "@/context/finans/BudgetContext";

export const PLATFORM_OPTIONS: Record<AssetType, string[]> = {
  vadesiz: [
    "Ziraat Bankası", "Garanti BBVA", "İş Bankası", "Akbank", "Yapı Kredi",
    "Halkbank", "VakıfBank", "Denizbank", "QNB Finansbank", "TEB",
    "HSBC Türkiye", "ING Bank", "Şekerbank", "Albaraka Türk", "Kuveyt Türk",
    "Türkiye Finans", "Fibabanka", "Burgan Bank", "ICBC Turkey", "Odea Bank",
    "Alternatif Bank", "Anadolubank", "Sekerbank", "Aktif Bank", "Milli Tasarruf Bankası",
  ],
  vadeli: [
    "Ziraat Bankası", "Garanti BBVA", "İş Bankası", "Akbank", "Yapı Kredi",
    "Halkbank", "VakıfBank", "Denizbank", "QNB Finansbank", "TEB",
    "HSBC Türkiye", "ING Bank", "Şekerbank", "Albaraka Türk", "Kuveyt Türk",
    "Türkiye Finans", "Fibabanka", "Burgan Bank", "ICBC Turkey", "Odea Bank",
  ],
  kripto: [
    "BtcTurk", "Paribu", "Bitexen", "Binance", "Coinbase", "Kraken",
    "OKX", "Bybit", "KuCoin", "Gate.io", "Huobi / HTX", "Bitfinex",
    "MEXC", "Bitget", "LBank", "CoinDCX", "Crypto.com", "Gemini",
    "Bitstamp", "Bitpanda", "Soğuk Cüzdan (Ledger)", "Soğuk Cüzdan (Trezor)",
    "MetaMask", "Trust Wallet",
  ],
  borsa: [
    "Midas", "İş Yatırım", "Garanti Yatırım", "Yapı Kredi Yatırım",
    "Gedik Yatırım", "AK Yatırım", "Deniz Yatırım", "TEB Yatırım",
    "Vakıf Yatırım", "Halk Yatırım", "Ziraat Yatırım", "Oyak Yatırım",
    "Şeker Yatırım", "Piramit Yatırım", "İnfo Yatırım", "Ahlatcı Yatırım",
    "GCM Yatırım", "Yatırım Finansman", "QNB Finans Yatırım", "Robo Yatırım",
  ],
  doviz: [
    "Ziraat Bankası", "Garanti BBVA", "İş Bankası", "Akbank", "Yapı Kredi",
    "Halkbank", "VakıfBank", "Kuveyt Türk", "Albaraka Türk", "Türkiye Finans",
    "Döviz Bürosu", "Borsa (VIOP)", "Western Union", "Wise",
  ],
  altin: [
    "Ziraat Bankası", "Garanti BBVA", "İş Bankası", "Akbank", "Halkbank",
    "VakıfBank", "Kuveyt Türk", "Albaraka Türk", "Altınbaş", "Darphane",
    "IAR (İstanbul Altın Rafinerisi)", "Fiziki (Evde)", "Güvenli Kasa",
  ],
};

export interface StockOption { ticker: string; name: string }
export interface CryptoOption { symbol: string; name: string }

export const BIST_STOCKS: StockOption[] = [
  { ticker: "AEFES", name: "Anadolu Efes Biracılık" },
  { ticker: "AGESA", name: "AgeSA Hayat ve Emeklilik" },
  { ticker: "AGHOL", name: "AG Anadolu Grubu Holding" },
  { ticker: "AGYO", name: "Atakule GYO" },
  { ticker: "AHGAZ", name: "Ahlatcı Doğalgaz Dağıtım" },
  { ticker: "AHSGY", name: "Ahlatcı GYO" },
  { ticker: "AKBNK", name: "Akbank" },
  { ticker: "AKCNS", name: "Akçansa Çimento" },
  { ticker: "AKENR", name: "Akenerji Elektrik Üretimi" },
  { ticker: "AKFGY", name: "Akiş GYO" },
  { ticker: "AKFYE", name: "Akfen Yenilenebilir Enerji" },
  { ticker: "AKGRT", name: "Aksigorta" },
  { ticker: "AKMGY", name: "Akmerkez GYO" },
  { ticker: "AKSA", name: "Aksa Akrilik Kimya" },
  { ticker: "AKSEN", name: "Aksa Enerji Üretim" },
  { ticker: "AKSGY", name: "Akiş GYO" },
  { ticker: "AKSUE", name: "Aksu Enerji" },
  { ticker: "ALARK", name: "Alarko Holding" },
  { ticker: "ALBRK", name: "Albaraka Türk" },
  { ticker: "ALCAR", name: "Alarko Carrier" },
  { ticker: "ALCTL", name: "Alcatel Lucent Teletaş" },
  { ticker: "ALFAS", name: "Alfa Solar Enerji" },
  { ticker: "ALGYO", name: "Alarko GYO" },
  { ticker: "ALKA", name: "Alkim Alkali Kimya" },
  { ticker: "ALKIM", name: "Alkim Kağıt Sanayi" },
  { ticker: "ALKLC", name: "Alkim Kimya" },
  { ticker: "ALMAD", name: "Altın Madeni" },
  { ticker: "ALTINS", name: "Altın Yunus Çeşme Turistik" },
  { ticker: "ALTNY", name: "Altınyunus Çeşme Turistik" },
  { ticker: "ALVES", name: "Alves" },
  { ticker: "ANELE", name: "Anel Elektrik Proje Taahhüt" },
  { ticker: "ANHYT", name: "Anadolu Hayat Emeklilik" },
  { ticker: "ANSGR", name: "Anadolu Sigorta" },
  { ticker: "ARASE", name: "Aras Kargo Yurt İçi Taşımacılık" },
  { ticker: "ARCLK", name: "Arçelik" },
  { ticker: "ARDYZ", name: "ARD Bilişim" },
  { ticker: "ARENA", name: "Arena Bilgisayar Sanayi" },
  { ticker: "ARSAN", name: "Arsan Tekstil" },
  { ticker: "ARTMS", name: "Artemis Gayrimenkul" },
  { ticker: "ASGYO", name: "Astaş GYO" },
  { ticker: "ASELS", name: "Aselsan Elektronik Sanayi" },
  { ticker: "ASUZU", name: "Anadolu Isuzu Otomotiv" },
  { ticker: "ATAGY", name: "Atağ GYO" },
  { ticker: "ATAKP", name: "Atak Perakende" },
  { ticker: "ATATP", name: "Ata Tarım Ürünleri" },
  { ticker: "ATEKS", name: "Ateks Giyim" },
  { ticker: "ATLAS", name: "Atlas Menkul Kıymetler" },
  { ticker: "ATSYH", name: "Atilla Sistemleri Yatırım Holding" },
  { ticker: "AVGYO", name: "Avrasya GYO" },
  { ticker: "AVHOL", name: "Avrasya Holding" },
  { ticker: "AVTUR", name: "Avrasya Gaz" },
  { ticker: "AYCES", name: "Altınyunus Çeşme Turistik" },
  { ticker: "AYDEM", name: "Aydem Yenilenebilir Enerji" },
  { ticker: "AYEN", name: "Ayen Enerji" },
  { ticker: "AZTEK", name: "Aztek Teknoloji" },
  { ticker: "BAGFS", name: "Bagfaş Bandırma Gübre Fabrikaları" },
  { ticker: "BAKAB", name: "Bak Ambalaj" },
  { ticker: "BANVT", name: "Banvit Bandırma Vitaminli Yem" },
  { ticker: "BARMA", name: "Baran Holding" },
  { ticker: "BASCM", name: "Başçimento" },
  { ticker: "BASGZ", name: "Başkent Doğalgaz Dağıtım" },
  { ticker: "BAYRK", name: "Bayrak Eğitim Yatırım Holding" },
  { ticker: "BERA", name: "Bera Holding" },
  { ticker: "BFREN", name: "Bosch Fren Sistemleri" },
  { ticker: "BIMAS", name: "BİM Birleşik Mağazalar" },
  { ticker: "BIZIM", name: "Bizim Toptan Satış Mağazaları" },
  { ticker: "BJKAS", name: "Beşiktaş Futbol Yatırımları" },
  { ticker: "BLCYT", name: "Bilici Yatırım" },
  { ticker: "BOBET", name: "Borusan Birleşik Boru Fabrikaları" },
  { ticker: "BORLS", name: "Borusan Lojistik" },
  { ticker: "BORSK", name: "Borova Orman" },
  { ticker: "BRISA", name: "Brisa Bridgestone Sabancı" },
  { ticker: "BRMEN", name: "Birleşim Mühendislik" },
  { ticker: "BRSAN", name: "Borçelik Çelik Sanayi" },
  { ticker: "BRYAT", name: "Birikim Yatırım Holding" },
  { ticker: "BSOKE", name: "Batısöke Söke Çimento" },
  { ticker: "BTCIM", name: "Batıçim Batı Anadolu Çimento" },
  { ticker: "BUCIM", name: "Bursa Çimento Fabrikası" },
  { ticker: "BURCE", name: "Burçelik" },
  { ticker: "BURVA", name: "Bursa Birleşik Vardar" },
  { ticker: "BVSAN", name: "Burçelik Vana" },
  { ticker: "CANTE", name: "Can Tarım ve Gıda" },
  { ticker: "CEMAS", name: "Cemaş Döküm Sanayi" },
  { ticker: "CEMTS", name: "Çemtaş Çelik Makine" },
  { ticker: "CEOEM", name: "CEO Event & Meeting" },
  { ticker: "CIMSA", name: "Çimsa Çimento Sanayi" },
  { ticker: "CLEBI", name: "Çelebi Hava Servisi" },
  { ticker: "CMBTN", name: "Çimbeton Hazır Beton" },
  { ticker: "CMENT", name: "Çimentaş İzmir Çimento" },
  { ticker: "COEUR", name: "Coeur Mining" },
  { ticker: "COSMO", name: "Cosmos Yatırım" },
  { ticker: "CRDFA", name: "Creditwest Faktoring" },
  { ticker: "CRFSA", name: "Carrefoursa Carrefour Sabancı" },
  { ticker: "CUSAN", name: "Cuhadaroğlu Metal" },
  { ticker: "CVKMD", name: "CVK Madencilik" },
  { ticker: "CWENE", name: "CW Enerji" },
  { ticker: "DAGHL", name: "Dağ Holding" },
  { ticker: "DAPGM", name: "Dap Yapı" },
  { ticker: "DARDL", name: "Dardanel Önentaş Gıda" },
  { ticker: "DENGE", name: "Denge Yatırım Holding" },
  { ticker: "DENIZ", name: "Denizbank" },
  { ticker: "DERIM", name: "Deri Holding" },
  { ticker: "DESPC", name: "Despec Bilgisayar" },
  { ticker: "DEVA", name: "Deva Holding" },
  { ticker: "DGATE", name: "Datagate Bilgisayar" },
  { ticker: "DGGYO", name: "Doğan GYO" },
  { ticker: "DHL", name: "DHL Global Forwarding" },
  { ticker: "DOAS", name: "Doğuş Otomotiv" },
  { ticker: "DOBUR", name: "Doğan Burda Dergi Yayıncılık" },
  { ticker: "DOCO", name: "Do & Co" },
  { ticker: "DOGUB", name: "Doğuş Holding" },
  { ticker: "DOHOL", name: "Doğan Holding" },
  { ticker: "DOKTA", name: "Döktaş Dökümcülük" },
  { ticker: "DURDO", name: "Duran Doğan Basım" },
  { ticker: "DYOBY", name: "DYO Boya Fabrikaları" },
  { ticker: "DZGYO", name: "Deniz GYO" },
  { ticker: "ECILC", name: "Eczacıbaşı İlaç Sanayi" },
  { ticker: "ECZYT", name: "Eczacıbaşı Yatırım" },
  { ticker: "EDIP", name: "Edip Gayrimenkul" },
  { ticker: "EGEEN", name: "Ege Endüstri ve Ticaret" },
  { ticker: "EGEPO", name: "Ege Profil Ticaret" },
  { ticker: "EGGUB", name: "Ege Gübre Sanayi" },
  { ticker: "EGPRO", name: "Ege Profil" },
  { ticker: "EGSER", name: "Ege Seramik" },
  { ticker: "EKGYO", name: "Emlak Konut GYO" },
  { ticker: "EKSUN", name: "Eksun Gıda" },
  { ticker: "ELITE", name: "Elite Naturel" },
  { ticker: "EMKEL", name: "Emkel Plastik" },
  { ticker: "EMNIS", name: "Eminönü İş" },
  { ticker: "ENKAI", name: "Enka İnşaat ve Sanayi" },
  { ticker: "ENSRI", name: "Enerjisa Enerji" },
  { ticker: "EPLAS", name: "EGE PLAST" },
  { ticker: "ERBOS", name: "Erbosan Erciyas Boru" },
  { ticker: "EREGL", name: "Ereğli Demir Çelik" },
  { ticker: "ERSU", name: "Ersu Meyve ve Gıda" },
  { ticker: "ESCOM", name: "Escort Teknoloji" },
  { ticker: "ESEN", name: "Esen Tarım" },
  { ticker: "EUHOL", name: "Euro Yatırım Holding" },
  { ticker: "EUREN", name: "Euro Enerji" },
  { ticker: "EURPK", name: "Europak Ambalaj" },
  { ticker: "EUYO", name: "Euro Yatırım Ortaklığı" },
  { ticker: "EYGYO", name: "Eyüpsultan GYO" },
  { ticker: "FADE", name: "Fade Gıda" },
  { ticker: "FENER", name: "Fenerbahçe Futbol" },
  { ticker: "FMIZP", name: "Farmhouse Gıda" },
  { ticker: "FONET", name: "Fonet Bilgi Teknolojileri" },
  { ticker: "FORMT", name: "Format Matbaacılık" },
  { ticker: "FORTE", name: "Forte Girişim Sermayesi" },
  { ticker: "FROTO", name: "Ford Otosan" },
  { ticker: "FZLGY", name: "Fırat GYO" },
  { ticker: "GARAN", name: "Garanti BBVA" },
  { ticker: "GARFA", name: "Garanti BBVA Faktoring" },
  { ticker: "GEDIK", name: "Gedik Yatırım" },
  { ticker: "GEDZA", name: "Gediz Ambalaj" },
  { ticker: "GENIL", name: "Gen İlaç" },
  { ticker: "GENTS", name: "Gentaş Genel Metal" },
  { ticker: "GEREL", name: "Gersan Elektrik" },
  { ticker: "GESAN", name: "Gersan Elektrik" },
  { ticker: "GLYHO", name: "Global Yatırım Holding" },
  { ticker: "GMTAS", name: "Gimtaş" },
  { ticker: "GOODY", name: "Goodyear Lastikleri" },
  { ticker: "GOZDE", name: "Gözde Girişim" },
  { ticker: "GRSEL", name: "Güriş Sel" },
  { ticker: "GRTRK", name: "Gürteks Tekstil" },
  { ticker: "GSRAY", name: "Galatasaray Sportif" },
  { ticker: "GUBRF", name: "Gübre Fabrikaları" },
  { ticker: "GUNDG", name: "Gündem Yayıncılık" },
  { ticker: "GUSGR", name: "Güneş Sigorta" },
  { ticker: "HALKB", name: "Halkbank" },
  { ticker: "HATEK", name: "Hateks Hatay Tekstil" },
  { ticker: "HDFGS", name: "Hedef Girişim Sermayesi" },
  { ticker: "HEDEF", name: "Hedef Holding" },
  { ticker: "HEKTS", name: "Hektaş Ticaret" },
  { ticker: "HLGYO", name: "Halk GYO" },
  { ticker: "HOROZ", name: "Horoz Lojistik" },
  { ticker: "HRKET", name: "Hürriyet Gazetecilik" },
  { ticker: "HTTBT", name: "Hattat Holding" },
  { ticker: "HUBVC", name: "Hub Girişim" },
  { ticker: "HUNER", name: "Hünkar Enerji" },
  { ticker: "HURGZ", name: "Hürriyet Gazetecilik" },
  { ticker: "ICBCT", name: "ICBC Turkey Bank" },
  { ticker: "IDEAS", name: "İdeas Mühendislik" },
  { ticker: "IDGYO", name: "İdeal GYO" },
  { ticker: "IEYHO", name: "İEYAS Holding" },
  { ticker: "IGDAS", name: "İstanbul Gaz Dağıtım" },
  { ticker: "IHEVA", name: "İhlas Ev Aletleri" },
  { ticker: "IHGZT", name: "İhlas Gazetecilik" },
  { ticker: "IHLAS", name: "İhlas Holding" },
  { ticker: "IHLGM", name: "İhlas Gayrimenkul" },
  { ticker: "IHYAY", name: "İhlas Yayın Holding" },
  { ticker: "IMASM", name: "İmas Makine" },
  { ticker: "INDES", name: "İndeks Bilgisayar" },
  { ticker: "INFO", name: "İnfo Yatırım" },
  { ticker: "INGRM", name: "Ingram Mikro" },
  { ticker: "INTEM", name: "İntem Holding" },
  { ticker: "INVEO", name: "İnveo Varlık Yönetimi" },
  { ticker: "IPEKE", name: "İpek Doğal Enerji" },
  { ticker: "ISATR", name: "İş Sanat" },
  { ticker: "ISCTR", name: "İş Bankası" },
  { ticker: "ISFIN", name: "İş Finansal Kiralama" },
  { ticker: "ISGSY", name: "İş GYO" },
  { ticker: "ISGYO", name: "İş Gayrimenkul Yatırım" },
  { ticker: "ISYAT", name: "İş Yatırım Menkul Değerler" },
  { ticker: "ITTFH", name: "İttifak Holding" },
  { ticker: "IZFAS", name: "İzmir Fuar" },
  { ticker: "IZINV", name: "İzmir Yatırım" },
  { ticker: "JANTS", name: "Jantsa Jant Sanayi" },
  { ticker: "KAPLM", name: "Kaplamin Ambalaj" },
  { ticker: "KARCE", name: "Karçelik" },
  { ticker: "KAREL", name: "Karel Elektronik" },
  { ticker: "KARSN", name: "Karsan Otomotiv" },
  { ticker: "KARTN", name: "Kartonsan Karton Sanayi" },
  { ticker: "KATMR", name: "Katmerciler Araç Üstü" },
  { ticker: "KAYSE", name: "Kayseri Şeker Fabrikası" },
  { ticker: "KCAER", name: "Kocaer Çelik" },
  { ticker: "KCHOL", name: "Koç Holding" },
  { ticker: "KENT", name: "Kent Gıda Maddeleri" },
  { ticker: "KERVN", name: "Kervan Gıda" },
  { ticker: "KGYO", name: "Kiler GYO" },
  { ticker: "KILER", name: "Kiler Alışveriş Hizmetleri" },
  { ticker: "KLKIM", name: "Kalekim Kimyevi Maddeler" },
  { ticker: "KLNMA", name: "Türkiye Kalkınma ve Yatırım Bankası" },
  { ticker: "KLRHO", name: "Kiler Alışveriş Holding" },
  { ticker: "KLSYN", name: "Kalyon Güneş" },
  { ticker: "KMPUR", name: "Kâmil Pür" },
  { ticker: "KNFRT", name: "Konfrut Gıda" },
  { ticker: "KONTR", name: "Kontrolmatik Teknoloji" },
  { ticker: "KONYA", name: "Konya Çimento" },
  { ticker: "KORDS", name: "Kordsa Teknik Tekstil" },
  { ticker: "KOZAA", name: "Koza Anadolu Metal" },
  { ticker: "KOZAL", name: "Koza Altın İşletmeleri" },
  { ticker: "KRDMA", name: "Kardemir Karabük Demir Çelik A" },
  { ticker: "KRDMB", name: "Kardemir Karabük Demir Çelik B" },
  { ticker: "KRDMD", name: "Kardemir Karabük Demir Çelik D" },
  { ticker: "KRGYO", name: "Körfez GYO" },
  { ticker: "KRPLAS", name: "Kron Telekomünikasyon" },
  { ticker: "KRSTL", name: "Kristal Kola" },
  { ticker: "KRTEK", name: "Kron Telekom" },
  { ticker: "KRVGD", name: "Karvi Gıda" },
  { ticker: "KSTUR", name: "Kuştur Kuşadası Turizm" },
  { ticker: "KTLEV", name: "Katılım Emeklilik" },
  { ticker: "KUTPO", name: "Kütahya Porselen" },
  { ticker: "KUYAS", name: "Kuyas Şeker Fabrikası" },
  { ticker: "LIDER", name: "Lider Faktoring" },
  { ticker: "LIDFA", name: "Lider Faktoring" },
  { ticker: "LINK", name: "Link Bilgisayar" },
  { ticker: "LKMNH", name: "Lokman Hekim" },
  { ticker: "LOGO", name: "Logo Yazılım" },
  { ticker: "LRSHO", name: "Lares Holding" },
  { ticker: "LUKSK", name: "Lüks Kadife" },
  { ticker: "MAALT", name: "Maalt Alüminyum" },
  { ticker: "MACKO", name: "Mackolik" },
  { ticker: "MAKTK", name: "Maktek Makine" },
  { ticker: "MANAS", name: "Manas Enerji" },
  { ticker: "MAVI", name: "Mavi Giyim" },
  { ticker: "MEDTR", name: "Meditera Tıbbi Malzeme" },
  { ticker: "MEGAP", name: "Mega Polietilen" },
  { ticker: "MEPET", name: "Mepet Metro Petrol" },
  { ticker: "MERCN", name: "Mercan Kimya" },
  { ticker: "MERIT", name: "Merit Turizm" },
  { ticker: "MERKO", name: "Merko Gıda" },
  { ticker: "METRO", name: "Metro Holding" },
  { ticker: "METUR", name: "Metur Turizm" },
  { ticker: "MGROS", name: "Migros Ticaret" },
  { ticker: "MIPAZ", name: "Milpa Ticari Pazarlama" },
  { ticker: "MMCAS", name: "MMC San Ticaret" },
  { ticker: "MNDRS", name: "Menderes Tekstil" },
  { ticker: "MNDTR", name: "Menderes Tekstil" },
  { ticker: "MOBTL", name: "Mobil Telekom" },
  { ticker: "MOGAN", name: "Mogan Teknoloji" },
  { ticker: "MPARK", name: "MLP Sağlık" },
  { ticker: "MRGYO", name: "Mardin GYO" },
  { ticker: "MRSHL", name: "Marshall Boya" },
  { ticker: "MSGYO", name: "Mistral GYO" },
  { ticker: "MTRKS", name: "Matriks Bilgi Dağıtım" },
  { ticker: "MZHLD", name: "Mozaik Yatırım Holding" },
  { ticker: "NATEN", name: "Naturel Enerji" },
  { ticker: "NETAS", name: "Netaş Telekomünikasyon" },
  { ticker: "NIBAS", name: "Niğde Beton" },
  { ticker: "NTHOL", name: "Net Holding" },
  { ticker: "NTTUR", name: "Net Turizm" },
  { ticker: "NUGYO", name: "Nurol GYO" },
  { ticker: "NUHCM", name: "Nuh Çimento Sanayi" },
  { ticker: "OBAMS", name: "OBA Market" },
  { ticker: "ODAS", name: "Odaş Elektrik" },
  { ticker: "OFSYM", name: "Ofis İstanbul" },
  { ticker: "ONCSM", name: "Öncü Girişim Sermayesi" },
  { ticker: "ORCAY", name: "Orçay Ortaköy" },
  { ticker: "ORGE", name: "Orge Enerji Elektrik" },
  { ticker: "ORMA", name: "Orma Orman Mahsulleri" },
  { ticker: "OSMEN", name: "Osmanli Menkul Değerler" },
  { ticker: "OSTIM", name: "Ostim Endüstriyel Yatırımlar" },
  { ticker: "OTKAR", name: "Otokar Otomotiv ve Savunma" },
  { ticker: "OYYAT", name: "Oyak Yatırım" },
  { ticker: "OZKGY", name: "Özak GYO" },
  { ticker: "OZRDN", name: "Özerden Plastik" },
  { ticker: "PAGYO", name: "Panora GYO" },
  { ticker: "PAPIL", name: "Papermill" },
  { ticker: "PARSN", name: "Parsan Makine" },
  { ticker: "PASEU", name: "Paşabahçe Cam" },
  { ticker: "PCILT", name: "Pınar Et ve Un Sanayii" },
  { ticker: "PEKGY", name: "Pektas GYO" },
  { ticker: "PENGD", name: "Penguen Gıda" },
  { ticker: "PENTA", name: "Penta Teknoloji" },
  { ticker: "PETKM", name: "Petkim Petrokimya" },
  { ticker: "PETUN", name: "Pınar Et ve Un Sanayii" },
  { ticker: "PGSUS", name: "Pegasus Havacılık" },
  { ticker: "PIMAS", name: "Plastik İplik" },
  { ticker: "PINSU", name: "Pınar Su" },
  { ticker: "PKART", name: "Plastikkart Akıllı" },
  { ticker: "PKENT", name: "Park Elektrik Üretim" },
  { ticker: "PLTUR", name: "Palandöken Turizm" },
  { ticker: "PNSUT", name: "Pınar Süt" },
  { ticker: "POLHO", name: "Polisan Holding" },
  { ticker: "POLTK", name: "Politeknik Metal" },
  { ticker: "PORTR", name: "Portakal" },
  { ticker: "PRDGS", name: "Perdegüneş" },
  { ticker: "PRZMA", name: "Prizma Pres" },
  { ticker: "PSDTC", name: "Persembe" },
  { ticker: "PTOFS", name: "Petrol Ofisi" },
  { ticker: "RALYH", name: "Raly Holding" },
  { ticker: "RAYSG", name: "Ray Sigorta" },
  { ticker: "REEDR", name: "Reeder Teknoloji" },
  { ticker: "REYSA", name: "Reysaş Taşımacılık" },
  { ticker: "RGYAS", name: "Reysaş GYO" },
  { ticker: "RNPOL", name: "Renaul Mais" },
  { ticker: "RODRG", name: "Rodrigo Tekstil" },
  { ticker: "ROYAL", name: "Royal Halı" },
  { ticker: "RTALB", name: "RTA Laboratuvarları" },
  { ticker: "RUBNS", name: "Rubenis Tekstil" },
  { ticker: "RYGYO", name: "Reysaş Gayrimenkul" },
  { ticker: "RYSAS", name: "Reysaş Lojistik" },
  { ticker: "SAHOL", name: "Sabancı Holding" },
  { ticker: "SAMAT", name: "Saray Matbaacılık" },
  { ticker: "SANEL", name: "Sanel Elektrik" },
  { ticker: "SANFM", name: "Sanifoam" },
  { ticker: "SANKO", name: "Sanko Holding" },
  { ticker: "SARKY", name: "Sarkuysan Elektrolitik" },
  { ticker: "SASA", name: "SASA Polyester" },
  { ticker: "SAYAS", name: "Saray Halı" },
  { ticker: "SDTTR", name: "SDT Uzay ve Savunma" },
  { ticker: "SEGMN", name: "Segment İnteraktif" },
  { ticker: "SEKFK", name: "Şeker Faktoring" },
  { ticker: "SEKUR", name: "Şeker Sigorta" },
  { ticker: "SELEC", name: "Selçuk Ecza Deposu" },
  { ticker: "SELGD", name: "Selva Gıda Sanayii" },
  { ticker: "SELVA", name: "Selva Gıda" },
  { ticker: "SENET", name: "Senet Ödeme Sistemleri" },
  { ticker: "SEYKM", name: "Sey Kimya" },
  { ticker: "SILVR", name: "Silver Gayrimenkul" },
  { ticker: "SISE", name: "Türkiye Şişe ve Cam" },
  { ticker: "SKTAS", name: "Söktaş Tekstil" },
  { ticker: "SMART", name: "Smart Güneş Enerjisi" },
  { ticker: "SMRTG", name: "Smart GYO" },
  { ticker: "SNPAM", name: "Sanofi" },
  { ticker: "SOKM", name: "Şok Marketler" },
  { ticker: "SONME", name: "Sönmez Filament" },
  { ticker: "SRVGY", name: "Servet GYO" },
  { ticker: "SUMAS", name: "Sumaş Sunta Fabrikaları" },
  { ticker: "SUNTK", name: "Sunta Teknoloji" },
  { ticker: "SUWEN", name: "Suwen" },
  { ticker: "TABGD", name: "TAB Gıda" },
  { ticker: "TATGD", name: "Tat Gıda Sanayi" },
  { ticker: "TAVHL", name: "TAV Havalimanları" },
  { ticker: "TBORG", name: "Türk Tuborg" },
  { ticker: "TCELL", name: "Turkcell İletişim" },
  { ticker: "TDGYO", name: "Tad GYO" },
  { ticker: "TEKTU", name: "Tekfen Turizm" },
  { ticker: "TEZOL", name: "Tezol Kağıt" },
  { ticker: "THYAO", name: "Türk Hava Yolları" },
  { ticker: "TKFEN", name: "Tekfen Holding" },
  { ticker: "TKNSA", name: "Teknosa" },
  { ticker: "TLMAN", name: "Telemann Telekomünikasyon" },
  { ticker: "TMPOL", name: "Temapol Polimer" },
  { ticker: "TMSN", name: "Tumosan Motor ve Traktör" },
  { ticker: "TNZTP", name: "Tanz Turizm" },
  { ticker: "TOASO", name: "Tofaş Türk Otomobil Fabrikası" },
  { ticker: "TRCAS", name: "Turcas Petrol" },
  { ticker: "TRGYO", name: "Torunlar GYO" },
  { ticker: "TRKCM", name: "Trakya Cam Sanayii" },
  { ticker: "TRKSY", name: "Türk Sınai Kalkınma" },
  { ticker: "TSKB", name: "Türkiye Sınai Kalkınma Bankası" },
  { ticker: "TSPOR", name: "Trabzonspor Sportif" },
  { ticker: "TTKOM", name: "Türk Telekom" },
  { ticker: "TTRAK", name: "Türk Traktör ve Ziraat Makineleri" },
  { ticker: "TUGVA", name: "Tuğva Eğitim" },
  { ticker: "TUKAS", name: "Tukaş Turgutlu Konserve" },
  { ticker: "TUPRS", name: "Tüpraş Türkiye Petrol Rafinerileri" },
  { ticker: "TUREX", name: "Turevex" },
  { ticker: "TURGG", name: "Türker Proje Gayrimenkul" },
  { ticker: "TURSG", name: "Türk Sigorta" },
  { ticker: "UFUK", name: "Ufuk Yatırım" },
  { ticker: "ULUFA", name: "Ulusoy Un" },
  { ticker: "ULUSE", name: "Ulusoy Elektrik" },
  { ticker: "ULUUN", name: "Ulusoy Un Sanayi" },
  { ticker: "ULKER", name: "Ülker Bisküvi" },
  { ticker: "UNLU", name: "Ünlü Yatırım" },
  { ticker: "USAK", name: "Uşak Seramik" },
  { ticker: "USSAS", name: "Uşak Şeker Fabrikası" },
  { ticker: "UTICO", name: "Uti Holding" },
  { ticker: "UYDUR", name: "Uydur Mimarlık" },
  { ticker: "VAKBN", name: "VakıfBank" },
  { ticker: "VAKFN", name: "Vakıf Finans Faktoring" },
  { ticker: "VAKGM", name: "Vakıf Gayrimenkul" },
  { ticker: "VANL", name: "Van Gıda" },
  { ticker: "VBTYZ", name: "VBT Yazılım" },
  { ticker: "VERUS", name: "Verus Yatırım" },
  { ticker: "VESBE", name: "Vestel Beyaz Eşya" },
  { ticker: "VESTL", name: "Vestel Elektronik" },
  { ticker: "VKFYO", name: "Vakıf Yatırım Ortaklığı" },
  { ticker: "VKGYO", name: "Vakıf GYO" },
  { ticker: "VRGYO", name: "Varlık GYO" },
  { ticker: "WINTA", name: "Wintermar Offshore" },
  { ticker: "WNTUR", name: "Win Turizm" },
  { ticker: "YATAS", name: "Yataş Yatak Yorgan" },
  { ticker: "YATGS", name: "Yatigaz Doğalgaz" },
  { ticker: "YBTAS", name: "Yıldız Boya Taahhüt" },
  { ticker: "YEOTK", name: "Yeo Teknoloji" },
  { ticker: "YESIL", name: "Yeşil GMYO" },
  { ticker: "YGGYO", name: "Yenigun GYO" },
  { ticker: "YGYO", name: "Yeni GYO" },
  { ticker: "YKSLN", name: "Yükselen Çelik" },
  { ticker: "YKSGR", name: "Yapı Kredi Sigorta" },
  { ticker: "YKBNK", name: "Yapı Kredi Bankası" },
  { ticker: "YKSRE", name: "Yükselen Çelik" },
  { ticker: "YLGYO", name: "Yıldız GYO" },
  { ticker: "YONGA", name: "Yonga Mobilya" },
  { ticker: "YYLGD", name: "Yayla Agro Gıda" },
  { ticker: "ZEDUR", name: "Zedur Enerji" },
  { ticker: "ZEREN", name: "Zerener Enerji" },
  { ticker: "ZRGYO", name: "Ziraat GYO" },
  { ticker: "ZRPAR", name: "Zirpara" },
];

export const CRYPTO_LIST: CryptoOption[] = [
  { symbol: "BTC",   name: "Bitcoin" },
  { symbol: "ETH",   name: "Ethereum" },
  { symbol: "BNB",   name: "Binance Coin" },
  { symbol: "SOL",   name: "Solana" },
  { symbol: "XRP",   name: "XRP (Ripple)" },
  { symbol: "USDT",  name: "Tether" },
  { symbol: "USDC",  name: "USD Coin" },
  { symbol: "ADA",   name: "Cardano" },
  { symbol: "AVAX",  name: "Avalanche" },
  { symbol: "DOGE",  name: "Dogecoin" },
  { symbol: "SHIB",  name: "Shiba Inu" },
  { symbol: "TRX",   name: "TRON" },
  { symbol: "DOT",   name: "Polkadot" },
  { symbol: "LINK",  name: "Chainlink" },
  { symbol: "MATIC", name: "Polygon (MATIC)" },
  { symbol: "LTC",   name: "Litecoin" },
  { symbol: "BCH",   name: "Bitcoin Cash" },
  { symbol: "UNI",   name: "Uniswap" },
  { symbol: "ATOM",  name: "Cosmos" },
  { symbol: "XLM",   name: "Stellar" },
  { symbol: "ETC",   name: "Ethereum Classic" },
  { symbol: "XMR",   name: "Monero" },
  { symbol: "ALGO",  name: "Algorand" },
  { symbol: "VET",   name: "VeChain" },
  { symbol: "FTM",   name: "Fantom" },
  { symbol: "NEAR",  name: "NEAR Protocol" },
  { symbol: "HBAR",  name: "Hedera" },
  { symbol: "GRT",   name: "The Graph" },
  { symbol: "AAVE",  name: "Aave" },
  { symbol: "ICP",   name: "Internet Computer" },
  { symbol: "FIL",   name: "Filecoin" },
  { symbol: "SAND",  name: "The Sandbox" },
  { symbol: "MANA",  name: "Decentraland" },
  { symbol: "AXS",   name: "Axie Infinity" },
  { symbol: "EGLD",  name: "MultiversX (Elrond)" },
  { symbol: "THETA", name: "Theta Network" },
  { symbol: "EOS",   name: "EOS" },
  { symbol: "XTZ",   name: "Tezos" },
  { symbol: "FLOW",  name: "Flow" },
  { symbol: "LUNA",  name: "Terra Classic" },
  { symbol: "LUNC",  name: "Terra Luna Classic" },
  { symbol: "ARB",   name: "Arbitrum" },
  { symbol: "OP",    name: "Optimism" },
  { symbol: "APT",   name: "Aptos" },
  { symbol: "SUI",   name: "Sui" },
  { symbol: "INJ",   name: "Injective" },
  { symbol: "STX",   name: "Stacks" },
  { symbol: "IMX",   name: "Immutable X" },
  { symbol: "MKR",   name: "Maker" },
  { symbol: "COMP",  name: "Compound" },
  { symbol: "CRV",   name: "Curve DAO" },
  { symbol: "SUSHI", name: "SushiSwap" },
  { symbol: "YFI",   name: "yearn.finance" },
  { symbol: "1INCH", name: "1inch" },
  { symbol: "BAL",   name: "Balancer" },
  { symbol: "CAKE",  name: "PancakeSwap" },
  { symbol: "SNX",   name: "Synthetix" },
  { symbol: "DASH",  name: "Dash" },
  { symbol: "ZEC",   name: "Zcash" },
  { symbol: "BAT",   name: "Basic Attention Token" },
  { symbol: "ZIL",   name: "Zilliqa" },
  { symbol: "QTUM",  name: "Qtum" },
  { symbol: "NEO",   name: "NEO" },
  { symbol: "ENJ",   name: "Enjin Coin" },
  { symbol: "CHZ",   name: "Chiliz" },
  { symbol: "IOTA",  name: "IOTA" },
  { symbol: "ROSE",  name: "Oasis Network" },
  { symbol: "KSM",   name: "Kusama" },
  { symbol: "KAVA",  name: "Kava" },
  { symbol: "ZEN",   name: "Horizen" },
  { symbol: "WAVES", name: "Waves" },
  { symbol: "ONT",   name: "Ontology" },
  { symbol: "ICX",   name: "ICON" },
  { symbol: "ZRX",   name: "0x" },
  { symbol: "STORJ", name: "Storj" },
  { symbol: "RVN",   name: "Ravencoin" },
  { symbol: "SC",    name: "Siacoin" },
  { symbol: "DGB",   name: "DigiByte" },
  { symbol: "DENT",  name: "Dent" },
  { symbol: "HOT",   name: "Holo" },
  { symbol: "WIN",   name: "WINkLink" },
  { symbol: "BTT",   name: "BitTorrent" },
  { symbol: "CELR",  name: "Celer Network" },
  { symbol: "ANKR",  name: "Ankr" },
  { symbol: "CELO",  name: "Celo" },
  { symbol: "RSR",   name: "Reserve Rights" },
  { symbol: "SKL",   name: "SKALE" },
  { symbol: "OGN",   name: "Origin Protocol" },
  { symbol: "LRC",   name: "Loopring" },
  { symbol: "CVC",   name: "Civic" },
  { symbol: "MTL",   name: "Metal DAO" },
  { symbol: "NMR",   name: "Numeraire" },
  { symbol: "OCEAN", name: "Ocean Protocol" },
  { symbol: "FET",   name: "Fetch.ai" },
  { symbol: "AGIX",  name: "SingularityNET" },
  { symbol: "RNDR",  name: "Render" },
  { symbol: "WLD",   name: "Worldcoin" },
  { symbol: "TON",   name: "Toncoin" },
  { symbol: "PEPE",  name: "Pepe" },
  { symbol: "FLOKI", name: "Floki" },
  { symbol: "BONK",  name: "Bonk" },
  { symbol: "WIF",   name: "dogwifhat" },
  { symbol: "JUP",   name: "Jupiter" },
  { symbol: "JTO",   name: "Jito" },
  { symbol: "PYTH",  name: "Pyth Network" },
  { symbol: "TIA",   name: "Celestia" },
  { symbol: "SEI",   name: "Sei" },
  { symbol: "BLUR",  name: "Blur" },
  { symbol: "HFT",   name: "Hashflow" },
  { symbol: "GMT",   name: "GMT (STEPN)" },
  { symbol: "APE",   name: "ApeCoin" },
  { symbol: "LDO",   name: "Lido DAO" },
  { symbol: "RPL",   name: "Rocket Pool" },
  { symbol: "PENDLE",name: "Pendle" },
  { symbol: "GMX",   name: "GMX" },
  { symbol: "DYDX",  name: "dYdX" },
  { symbol: "PERP",  name: "Perpetual Protocol" },
  { symbol: "RUNE",  name: "THORChain" },
  { symbol: "OSMO",  name: "Osmosis" },
  { symbol: "JUNO",  name: "Juno" },
  { symbol: "SCRT",  name: "Secret" },
  { symbol: "EVMOS", name: "Evmos" },
  { symbol: "KUJI",  name: "Kujira" },
  { symbol: "MINA",  name: "Mina Protocol" },
  { symbol: "CFX",   name: "Conflux" },
  { symbol: "CORE",  name: "Core" },
  { symbol: "ONDO",  name: "Ondo" },
  { symbol: "ENA",   name: "Ethena" },
  { symbol: "MEW",   name: "cat in a dogs world" },
  { symbol: "NOT",   name: "Notcoin" },
  { symbol: "DOGS",  name: "DOGS" },
  { symbol: "HMSTR", name: "Hamster Kombat" },
  { symbol: "CATI",  name: "Catizen" },
  { symbol: "MAJOR", name: "Major" },
  { symbol: "EIGEN", name: "Eigenlayer" },
  { symbol: "POL",   name: "POL (Polygon 2.0)" },
  { symbol: "VIRTUAL","name": "Virtuals Protocol" },
  { symbol: "AI16Z", name: "ai16z" },
  { symbol: "FARTCOIN","name": "Fartcoin" },
  { symbol: "ACT",   name: "Act I : The AI Prophecy" },
  { symbol: "TRUMP", name: "OFFICIAL TRUMP" },
  { symbol: "MELANIA","name": "MELANIA" },
  { symbol: "PNUT",  name: "Peanut the Squirrel" },
  { symbol: "MOODENG","name": "moo deng" },
  { symbol: "SPX",   name: "SPX6900" },
  { symbol: "POPCAT","name": "Popcat" },
];

export interface ForexOption { code: string; name: string }
export interface GoldOption  { key: string; label: string }

export const FOREX_LIST: ForexOption[] = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "AED", name: "UAE Dirham" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "DKK", name: "Danish Krone" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "INR", name: "Indian Rupee" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "ZAR", name: "South African Rand" },
];

export const GOLD_LIST: GoldOption[] = [
  { key: "gram", label: "Gram Altın (XAU)" },
  { key: "oz",   label: "Ons Altın (XAU)" },
];

// ── Stock Index Types & Data ────────────────────────────────────────────────

export interface StockIndex {
  id: string;
  label: string;
  country: string;
  flag: string;
  exchangeSuffix: string; // e.g. ".IS", ".DE", "" (US)
  currency: string;       // "TRY" | "USD" | "EUR" | "GBP" | "JPY" etc.
  priceDivisor?: number;  // e.g. 100 for LSE stocks quoted in pence
  stocks: StockOption[];
}

// ── NASDAQ 100 ─────────────────────────────────────────────────────────────
const NASDAQ_100: StockOption[] = [
  { ticker: "AAPL",   name: "Apple" },
  { ticker: "MSFT",   name: "Microsoft" },
  { ticker: "NVDA",   name: "NVIDIA" },
  { ticker: "AMZN",   name: "Amazon" },
  { ticker: "GOOGL",  name: "Alphabet (Sınıf A)" },
  { ticker: "GOOG",   name: "Alphabet (Sınıf C)" },
  { ticker: "META",   name: "Meta Platforms" },
  { ticker: "TSLA",   name: "Tesla" },
  { ticker: "AVGO",   name: "Broadcom" },
  { ticker: "COST",   name: "Costco Wholesale" },
  { ticker: "NFLX",   name: "Netflix" },
  { ticker: "AMD",    name: "Advanced Micro Devices" },
  { ticker: "ASML",   name: "ASML Holding" },
  { ticker: "ADBE",   name: "Adobe" },
  { ticker: "QCOM",   name: "Qualcomm" },
  { ticker: "INTU",   name: "Intuit" },
  { ticker: "TXN",    name: "Texas Instruments" },
  { ticker: "AMGN",   name: "Amgen" },
  { ticker: "HON",    name: "Honeywell International" },
  { ticker: "AMAT",   name: "Applied Materials" },
  { ticker: "BKNG",   name: "Booking Holdings" },
  { ticker: "ISRG",   name: "Intuitive Surgical" },
  { ticker: "MU",     name: "Micron Technology" },
  { ticker: "PANW",   name: "Palo Alto Networks" },
  { ticker: "LRCX",   name: "Lam Research" },
  { ticker: "KLAC",   name: "KLA Corporation" },
  { ticker: "SNPS",   name: "Synopsys" },
  { ticker: "CDNS",   name: "Cadence Design Systems" },
  { ticker: "MELI",   name: "MercadoLibre" },
  { ticker: "CRWD",   name: "CrowdStrike Holdings" },
  { ticker: "REGN",   name: "Regeneron Pharmaceuticals" },
  { ticker: "VRTX",   name: "Vertex Pharmaceuticals" },
  { ticker: "SBUX",   name: "Starbucks" },
  { ticker: "GILD",   name: "Gilead Sciences" },
  { ticker: "ADP",    name: "Automatic Data Processing" },
  { ticker: "MRVL",   name: "Marvell Technology" },
  { ticker: "ORLY",   name: "O'Reilly Automotive" },
  { ticker: "NXPI",   name: "NXP Semiconductors" },
  { ticker: "FTNT",   name: "Fortinet" },
  { ticker: "MNST",   name: "Monster Beverage" },
  { ticker: "PYPL",   name: "PayPal Holdings" },
  { ticker: "ROST",   name: "Ross Stores" },
  { ticker: "CPRT",   name: "Copart" },
  { ticker: "DXCM",   name: "DexCom" },
  { ticker: "ABNB",   name: "Airbnb" },
  { ticker: "ZS",     name: "Zscaler" },
  { ticker: "ODFL",   name: "Old Dominion Freight Line" },
  { ticker: "FAST",   name: "Fastenal" },
  { ticker: "CTAS",   name: "Cintas" },
  { ticker: "PAYX",   name: "Paychex" },
  { ticker: "GEHC",   name: "GE HealthCare Technologies" },
  { ticker: "IDXX",   name: "IDEXX Laboratories" },
  { ticker: "CEG",    name: "Constellation Energy" },
  { ticker: "TTD",    name: "The Trade Desk" },
  { ticker: "DDOG",   name: "Datadog" },
  { ticker: "VRSK",   name: "Verisk Analytics" },
  { ticker: "BIIB",   name: "Biogen" },
  { ticker: "CHTR",   name: "Charter Communications" },
  { ticker: "PCAR",   name: "PACCAR" },
  { ticker: "LULU",   name: "Lululemon Athletica" },
  { ticker: "ON",     name: "ON Semiconductor" },
  { ticker: "EXC",    name: "Exelon" },
  { ticker: "KDP",    name: "Keurig Dr Pepper" },
  { ticker: "DLTR",   name: "Dollar Tree" },
  { ticker: "CTSH",   name: "Cognizant Technology" },
  { ticker: "EA",     name: "Electronic Arts" },
  { ticker: "TEAM",   name: "Atlassian" },
  { ticker: "XEL",    name: "Xcel Energy" },
  { ticker: "ARM",    name: "Arm Holdings" },
  { ticker: "APP",    name: "Applovin" },
  { ticker: "INTC",   name: "Intel" },
  { ticker: "CSX",    name: "CSX Corporation" },
  { ticker: "CCEP",   name: "Coca-Cola Europacific Partners" },
  { ticker: "CDW",    name: "CDW Corporation" },
  { ticker: "FANG",   name: "Diamondback Energy" },
];

// ── S&P 500 (top bileşenler) ───────────────────────────────────────────────
const SP500_TOP: StockOption[] = [
  { ticker: "AAPL",   name: "Apple" },
  { ticker: "MSFT",   name: "Microsoft" },
  { ticker: "NVDA",   name: "NVIDIA" },
  { ticker: "AMZN",   name: "Amazon" },
  { ticker: "GOOGL",  name: "Alphabet (Sınıf A)" },
  { ticker: "META",   name: "Meta Platforms" },
  { ticker: "TSLA",   name: "Tesla" },
  { ticker: "AVGO",   name: "Broadcom" },
  { ticker: "BRK-B",  name: "Berkshire Hathaway" },
  { ticker: "LLY",    name: "Eli Lilly" },
  { ticker: "JPM",    name: "JPMorgan Chase" },
  { ticker: "UNH",    name: "UnitedHealth Group" },
  { ticker: "XOM",    name: "ExxonMobil" },
  { ticker: "V",      name: "Visa" },
  { ticker: "MA",     name: "Mastercard" },
  { ticker: "COST",   name: "Costco Wholesale" },
  { ticker: "PG",     name: "Procter & Gamble" },
  { ticker: "JNJ",    name: "Johnson & Johnson" },
  { ticker: "HD",     name: "Home Depot" },
  { ticker: "WMT",    name: "Walmart" },
  { ticker: "ABBV",   name: "AbbVie" },
  { ticker: "MRK",    name: "Merck" },
  { ticker: "KO",     name: "Coca-Cola" },
  { ticker: "PEP",    name: "PepsiCo" },
  { ticker: "CVX",    name: "Chevron" },
  { ticker: "NFLX",   name: "Netflix" },
  { ticker: "AMD",    name: "Advanced Micro Devices" },
  { ticker: "ORCL",   name: "Oracle" },
  { ticker: "CRM",    name: "Salesforce" },
  { ticker: "ACN",    name: "Accenture" },
  { ticker: "MCD",    name: "McDonald's" },
  { ticker: "WFC",    name: "Wells Fargo" },
  { ticker: "LIN",    name: "Linde" },
  { ticker: "DHR",    name: "Danaher" },
  { ticker: "PM",     name: "Philip Morris International" },
  { ticker: "ABT",    name: "Abbott Laboratories" },
  { ticker: "IBM",    name: "IBM" },
  { ticker: "CAT",    name: "Caterpillar" },
  { ticker: "GE",     name: "GE Aerospace" },
  { ticker: "INTU",   name: "Intuit" },
  { ticker: "TXN",    name: "Texas Instruments" },
  { ticker: "HON",    name: "Honeywell International" },
  { ticker: "BA",     name: "Boeing" },
  { ticker: "T",      name: "AT&T" },
  { ticker: "VZ",     name: "Verizon Communications" },
  { ticker: "DIS",    name: "Walt Disney" },
  { ticker: "RTX",    name: "RTX Corporation" },
  { ticker: "GS",     name: "Goldman Sachs" },
  { ticker: "SPGI",   name: "S&P Global" },
  { ticker: "BLK",    name: "BlackRock" },
  { ticker: "AMGN",   name: "Amgen" },
  { ticker: "MS",     name: "Morgan Stanley" },
  { ticker: "SCHW",   name: "Charles Schwab" },
  { ticker: "AXP",    name: "American Express" },
  { ticker: "NEE",    name: "NextEra Energy" },
  { ticker: "UPS",    name: "United Parcel Service" },
  { ticker: "LOW",    name: "Lowe's Companies" },
  { ticker: "ISRG",   name: "Intuitive Surgical" },
  { ticker: "BMY",    name: "Bristol-Myers Squibb" },
  { ticker: "C",      name: "Citigroup" },
  { ticker: "MDLZ",   name: "Mondelez International" },
  { ticker: "VRTX",   name: "Vertex Pharmaceuticals" },
  { ticker: "REGN",   name: "Regeneron Pharmaceuticals" },
  { ticker: "DE",     name: "Deere & Company" },
  { ticker: "TJX",    name: "TJX Companies" },
  { ticker: "MO",     name: "Altria Group" },
  { ticker: "ETN",    name: "Eaton Corporation" },
  { ticker: "SO",     name: "Southern Company" },
  { ticker: "ZTS",    name: "Zoetis" },
  { ticker: "PANW",   name: "Palo Alto Networks" },
  { ticker: "NKE",    name: "Nike" },
  { ticker: "UBER",   name: "Uber Technologies" },
  { ticker: "BAC",    name: "Bank of America" },
  { ticker: "F",      name: "Ford Motor" },
  { ticker: "GM",     name: "General Motors" },
  { ticker: "PLTR",   name: "Palantir Technologies" },
  { ticker: "COIN",   name: "Coinbase Global" },
];

// ── Dow Jones 30 ───────────────────────────────────────────────────────────
const DOW_30: StockOption[] = [
  { ticker: "AAPL",   name: "Apple" },
  { ticker: "MSFT",   name: "Microsoft" },
  { ticker: "UNH",    name: "UnitedHealth Group" },
  { ticker: "GS",     name: "Goldman Sachs" },
  { ticker: "HD",     name: "Home Depot" },
  { ticker: "MCD",    name: "McDonald's" },
  { ticker: "CAT",    name: "Caterpillar" },
  { ticker: "AMGN",   name: "Amgen" },
  { ticker: "V",      name: "Visa" },
  { ticker: "TRV",    name: "Travelers Companies" },
  { ticker: "SHW",    name: "Sherwin-Williams" },
  { ticker: "JNJ",    name: "Johnson & Johnson" },
  { ticker: "IBM",    name: "IBM" },
  { ticker: "AXP",    name: "American Express" },
  { ticker: "JPM",    name: "JPMorgan Chase" },
  { ticker: "CRM",    name: "Salesforce" },
  { ticker: "NKE",    name: "Nike" },
  { ticker: "HON",    name: "Honeywell" },
  { ticker: "WMT",    name: "Walmart" },
  { ticker: "NVDA",   name: "NVIDIA" },
  { ticker: "BA",     name: "Boeing" },
  { ticker: "CVX",    name: "Chevron" },
  { ticker: "PG",     name: "Procter & Gamble" },
  { ticker: "MMM",    name: "3M" },
  { ticker: "DIS",    name: "Walt Disney" },
  { ticker: "KO",     name: "Coca-Cola" },
  { ticker: "VZ",     name: "Verizon" },
  { ticker: "MRK",    name: "Merck" },
  { ticker: "CSCO",   name: "Cisco Systems" },
  { ticker: "INTC",   name: "Intel" },
];

// ── DAX 40 ─────────────────────────────────────────────────────────────────
const DAX_40: StockOption[] = [
  { ticker: "SAP",    name: "SAP SE" },
  { ticker: "SIE",    name: "Siemens" },
  { ticker: "ALV",    name: "Allianz" },
  { ticker: "MBG",    name: "Mercedes-Benz" },
  { ticker: "MUV2",   name: "Munich Re" },
  { ticker: "DTE",    name: "Deutsche Telekom" },
  { ticker: "BMW",    name: "BMW" },
  { ticker: "RWE",    name: "RWE" },
  { ticker: "DB1",    name: "Deutsche Börse" },
  { ticker: "BAS",    name: "BASF" },
  { ticker: "BAYN",   name: "Bayer" },
  { ticker: "ADS",    name: "Adidas" },
  { ticker: "HEI",    name: "HeidelbergMaterials" },
  { ticker: "IFX",    name: "Infineon Technologies" },
  { ticker: "AIR",    name: "Airbus" },
  { ticker: "ENR",    name: "Siemens Energy" },
  { ticker: "SHL",    name: "Siemens Healthineers" },
  { ticker: "EOAN",   name: "E.ON" },
  { ticker: "DHL",    name: "Deutsche Post" },
  { ticker: "VOW3",   name: "Volkswagen" },
  { ticker: "CON",    name: "Continental" },
  { ticker: "BNR",    name: "Brenntag" },
  { ticker: "VNA",    name: "Vonovia" },
  { ticker: "FRE",    name: "Fresenius" },
  { ticker: "FME",    name: "Fresenius Medical Care" },
  { ticker: "DTG",    name: "Daimler Truck" },
  { ticker: "DBK",    name: "Deutsche Bank" },
  { ticker: "CBK",    name: "Commerzbank" },
  { ticker: "RHM",    name: "Rheinmetall" },
  { ticker: "HNR1",   name: "Hannover Re" },
  { ticker: "MTX",    name: "MTU Aero Engines" },
  { ticker: "QIA",    name: "QIAGEN" },
  { ticker: "SY1",    name: "Symrise" },
  { ticker: "SRT3",   name: "Sartorius" },
  { ticker: "HEN3",   name: "Henkel" },
  { ticker: "PUM",    name: "Puma" },
  { ticker: "ZAL",    name: "Zalando" },
  { ticker: "1COV",   name: "Covestro" },
  { ticker: "PAH3",   name: "Porsche Automobil Holding" },
  { ticker: "P911",   name: "Porsche AG" },
];

// ── FTSE 100 ───────────────────────────────────────────────────────────────
const FTSE_100: StockOption[] = [
  { ticker: "AZN",    name: "AstraZeneca" },
  { ticker: "SHEL",   name: "Shell" },
  { ticker: "HSBA",   name: "HSBC Holdings" },
  { ticker: "ULVR",   name: "Unilever" },
  { ticker: "RIO",    name: "Rio Tinto" },
  { ticker: "BP",     name: "BP" },
  { ticker: "GSK",    name: "GSK" },
  { ticker: "REL",    name: "RELX" },
  { ticker: "DGE",    name: "Diageo" },
  { ticker: "NG",     name: "National Grid" },
  { ticker: "BATS",   name: "British American Tobacco" },
  { ticker: "BHP",    name: "BHP Group" },
  { ticker: "GLEN",   name: "Glencore" },
  { ticker: "AAL",    name: "Anglo American" },
  { ticker: "VOD",    name: "Vodafone Group" },
  { ticker: "LSEG",   name: "London Stock Exchange Group" },
  { ticker: "CPG",    name: "Compass Group" },
  { ticker: "RKT",    name: "Reckitt Benckiser" },
  { ticker: "BAE",    name: "BAE Systems" },
  { ticker: "PRU",    name: "Prudential" },
  { ticker: "AV",     name: "Aviva" },
  { ticker: "BARC",   name: "Barclays" },
  { ticker: "LLOY",   name: "Lloyds Banking Group" },
  { ticker: "NWG",    name: "NatWest Group" },
  { ticker: "TSCO",   name: "Tesco" },
  { ticker: "ABF",    name: "Associated British Foods" },
  { ticker: "IMB",    name: "Imperial Brands" },
  { ticker: "WTB",    name: "Whitbread" },
  { ticker: "SSE",    name: "SSE" },
  { ticker: "CNA",    name: "Centrica" },
  { ticker: "WPP",    name: "WPP" },
  { ticker: "BT-A",   name: "BT Group" },
  { ticker: "EXPN",   name: "Experian" },
  { ticker: "SGRO",   name: "Segro" },
  { ticker: "MKS",    name: "Marks & Spencer" },
  { ticker: "STAN",   name: "Standard Chartered" },
  { ticker: "FLTR",   name: "Flutter Entertainment" },
  { ticker: "RR",     name: "Rolls-Royce Holdings" },
  { ticker: "ITRK",   name: "Intertek Group" },
  { ticker: "LAND",   name: "Land Securities" },
  { ticker: "IAG",    name: "International Airlines Group" },
  { ticker: "EZJ",    name: "easyJet" },
  { ticker: "MNDI",   name: "Mondi" },
  { ticker: "SBRY",   name: "Sainsbury's" },
  { ticker: "SPX",    name: "Spirax Group" },
  { ticker: "HWDN",   name: "Howden Joinery Group" },
];

// ── CAC 40 ─────────────────────────────────────────────────────────────────
const CAC_40: StockOption[] = [
  { ticker: "MC",     name: "LVMH" },
  { ticker: "RMS",    name: "Hermès International" },
  { ticker: "TTE",    name: "TotalEnergies" },
  { ticker: "OR",     name: "L'Oréal" },
  { ticker: "SU",     name: "Schneider Electric" },
  { ticker: "AI",     name: "Air Liquide" },
  { ticker: "BNP",    name: "BNP Paribas" },
  { ticker: "CS",     name: "AXA" },
  { ticker: "SAF",    name: "Safran" },
  { ticker: "AIR",    name: "Airbus" },
  { ticker: "DG",     name: "Vinci" },
  { ticker: "GLE",    name: "Société Générale" },
  { ticker: "KER",    name: "Kering" },
  { ticker: "RI",     name: "Pernod Ricard" },
  { ticker: "ORA",    name: "Orange" },
  { ticker: "STM",    name: "STMicroelectronics" },
  { ticker: "ML",     name: "Michelin" },
  { ticker: "LR",     name: "Legrand" },
  { ticker: "PUB",    name: "Publicis Groupe" },
  { ticker: "EL",     name: "EssilorLuxottica" },
  { ticker: "DSY",    name: "Dassault Systèmes" },
  { ticker: "VIE",    name: "Veolia Environnement" },
  { ticker: "HO",     name: "Thales" },
  { ticker: "SGO",    name: "Saint-Gobain" },
  { ticker: "BN",     name: "Danone" },
  { ticker: "CAP",    name: "Capgemini" },
  { ticker: "EN",     name: "Bouygues" },
  { ticker: "ENGI",   name: "Engie" },
  { ticker: "MT",     name: "ArcelorMittal" },
  { ticker: "RNO",    name: "Renault" },
  { ticker: "CA",     name: "Carrefour" },
  { ticker: "AC",     name: "Accor" },
  { ticker: "ERF",    name: "Eurofins Scientific" },
  { ticker: "FGR",    name: "Eiffage" },
  { ticker: "STLAM",  name: "Stellantis" },
  { ticker: "SW",     name: "Sodexo" },
  { ticker: "FR",     name: "Valeo" },
  { ticker: "TEP",    name: "Teleperformance" },
  { ticker: "VIV",    name: "Vivendi" },
  { ticker: "ATO",    name: "Dassault Aviation" },
];

// ── Nikkei 225 (önemli bileşenler) ────────────────────────────────────────
const NIKKEI_TOP: StockOption[] = [
  { ticker: "7203",   name: "Toyota Motor" },
  { ticker: "6758",   name: "Sony Group" },
  { ticker: "9984",   name: "SoftBank Group" },
  { ticker: "6861",   name: "Keyence" },
  { ticker: "6098",   name: "Recruit Holdings" },
  { ticker: "9983",   name: "Fast Retailing (Uniqlo)" },
  { ticker: "8035",   name: "Tokyo Electron" },
  { ticker: "4063",   name: "Shin-Etsu Chemical" },
  { ticker: "6954",   name: "Fanuc" },
  { ticker: "6981",   name: "Murata Manufacturing" },
  { ticker: "9433",   name: "KDDI" },
  { ticker: "7974",   name: "Nintendo" },
  { ticker: "7267",   name: "Honda Motor" },
  { ticker: "6702",   name: "Fujitsu" },
  { ticker: "6501",   name: "Hitachi" },
  { ticker: "7751",   name: "Canon" },
  { ticker: "9432",   name: "NTT (Nippon Telegraph)" },
  { ticker: "8306",   name: "Mitsubishi UFJ Financial" },
  { ticker: "8411",   name: "Mizuho Financial Group" },
  { ticker: "8001",   name: "Itochu" },
  { ticker: "8053",   name: "Sumitomo Corporation" },
  { ticker: "5401",   name: "Nippon Steel" },
  { ticker: "6752",   name: "Panasonic Holdings" },
  { ticker: "4911",   name: "Shiseido" },
  { ticker: "6971",   name: "Kyocera" },
  { ticker: "8604",   name: "Nomura Holdings" },
  { ticker: "7011",   name: "Mitsubishi Heavy Industries" },
  { ticker: "4568",   name: "Daiichi Sankyo" },
  { ticker: "4502",   name: "Takeda Pharmaceutical" },
  { ticker: "6367",   name: "Daikin Industries" },
  { ticker: "6902",   name: "Denso" },
  { ticker: "4543",   name: "Terumo" },
  { ticker: "6273",   name: "SMC Corporation" },
  { ticker: "8766",   name: "Tokio Marine Holdings" },
  { ticker: "9022",   name: "Central Japan Railway" },
  { ticker: "3382",   name: "Seven & i Holdings" },
  { ticker: "9020",   name: "East Japan Railway" },
  { ticker: "6503",   name: "Mitsubishi Electric" },
  { ticker: "5108",   name: "Bridgestone" },
  { ticker: "4901",   name: "Fujifilm Holdings" },
  { ticker: "7261",   name: "Mazda Motor" },
  { ticker: "7201",   name: "Nissan Motor" },
  { ticker: "8316",   name: "Sumitomo Mitsui Financial" },
  { ticker: "9101",   name: "Nippon Yusen (NYK)" },
  { ticker: "2914",   name: "Japan Tobacco International" },
];

// ── BIST 30 ────────────────────────────────────────────────────────────────
const BIST_30: StockOption[] = [
  { ticker: "THYAO",  name: "Türk Hava Yolları" },
  { ticker: "GARAN",  name: "Garanti BBVA" },
  { ticker: "AKBNK",  name: "Akbank" },
  { ticker: "YKBNK",  name: "Yapı ve Kredi Bankası" },
  { ticker: "TUPRS",  name: "Tüpraş" },
  { ticker: "BIMAS",  name: "BİM Birleşik Mağazalar" },
  { ticker: "EREGL",  name: "Ereğli Demir Çelik" },
  { ticker: "SISE",   name: "Şişe Cam" },
  { ticker: "KCHOL",  name: "Koç Holding" },
  { ticker: "FROTO",  name: "Ford Otosan" },
  { ticker: "SAHOL",  name: "Sabancı Holding" },
  { ticker: "TOASO",  name: "Tofaş Otomobil Fab." },
  { ticker: "ARCLK",  name: "Arçelik" },
  { ticker: "HALKB",  name: "Halkbank" },
  { ticker: "VAKBN",  name: "Vakıfbank" },
  { ticker: "PETKM",  name: "Petkim" },
  { ticker: "ENKAI",  name: "Enka İnşaat" },
  { ticker: "ASELS",  name: "Aselsan" },
  { ticker: "KOZAL",  name: "Koza Altın İşletmeleri" },
  { ticker: "TTRAK",  name: "Türk Traktör" },
  { ticker: "ISCTR",  name: "İş Bankası C" },
  { ticker: "MGROS",  name: "Migros Ticaret" },
  { ticker: "TCELL",  name: "Turkcell" },
  { ticker: "PGSUS",  name: "Pegasus Hava Taşımacılığı" },
  { ticker: "EKGYO",  name: "Emlak Konut GYO" },
  { ticker: "SOKM",   name: "Şok Marketler" },
  { ticker: "CIMSA",  name: "Çimsa Çimento" },
  { ticker: "TAVHL",  name: "TAV Havalimanları" },
  { ticker: "SASA",   name: "SASA Polyester" },
  { ticker: "KONTR",  name: "Kontrolmatik Teknoloji" },
];

// ── Hang Seng ──────────────────────────────────────────────────────────────
const HANG_SENG: StockOption[] = [
  { ticker: "0700",   name: "Tencent Holdings" },
  { ticker: "9988",   name: "Alibaba Group" },
  { ticker: "0005",   name: "HSBC Holdings" },
  { ticker: "1299",   name: "AIA Group" },
  { ticker: "3690",   name: "Meituan" },
  { ticker: "0388",   name: "Hong Kong Exchanges (HKEx)" },
  { ticker: "0939",   name: "China Construction Bank" },
  { ticker: "1398",   name: "ICBC" },
  { ticker: "3988",   name: "Bank of China" },
  { ticker: "2318",   name: "Ping An Insurance" },
  { ticker: "0002",   name: "CLP Holdings" },
  { ticker: "0011",   name: "Hang Seng Bank" },
  { ticker: "0016",   name: "Sun Hung Kai Properties" },
  { ticker: "0001",   name: "CK Hutchison Holdings" },
  { ticker: "0823",   name: "Link REIT" },
  { ticker: "0066",   name: "MTR Corporation" },
  { ticker: "0027",   name: "Galaxy Entertainment" },
  { ticker: "1928",   name: "Sands China" },
  { ticker: "0883",   name: "CNOOC" },
  { ticker: "0857",   name: "PetroChina" },
  { ticker: "1211",   name: "BYD Company" },
  { ticker: "9999",   name: "NetEase" },
  { ticker: "9618",   name: "JD.com" },
  { ticker: "1810",   name: "Xiaomi Corporation" },
  { ticker: "0941",   name: "China Mobile" },
  { ticker: "0728",   name: "China Telecom" },
  { ticker: "0175",   name: "Geely Automobile" },
  { ticker: "2333",   name: "Great Wall Motor" },
  { ticker: "0669",   name: "Techtronic Industries" },
  { ticker: "2688",   name: "ENN Energy Holdings" },
  { ticker: "0960",   name: "Longfor Properties" },
  { ticker: "1113",   name: "CK Asset Holdings" },
  { ticker: "0992",   name: "Lenovo Group" },
  { ticker: "2628",   name: "China Life Insurance" },
  { ticker: "0688",   name: "China Overseas Land & Inv." },
  { ticker: "0012",   name: "Henderson Land Development" },
  { ticker: "1109",   name: "China Resources Land" },
  { ticker: "0981",   name: "SMIC" },
  { ticker: "2382",   name: "Sunny Optical Technology" },
  { ticker: "0019",   name: "Swire Pacific" },
  { ticker: "1177",   name: "Sino Biopharmaceutical" },
  { ticker: "0006",   name: "Power Assets Holdings" },
  { ticker: "0017",   name: "New World Development" },
  { ticker: "3319",   name: "Mao Geping Cosmetics" },
  { ticker: "1038",   name: "CK Infrastructure Holdings" },
];

// ── KOSPI ──────────────────────────────────────────────────────────────────
const KOSPI_TOP: StockOption[] = [
  { ticker: "005930", name: "Samsung Electronics" },
  { ticker: "000660", name: "SK Hynix" },
  { ticker: "373220", name: "LG Energy Solution" },
  { ticker: "207940", name: "Samsung Biologics" },
  { ticker: "006400", name: "Samsung SDI" },
  { ticker: "005380", name: "Hyundai Motor" },
  { ticker: "068270", name: "Celltrion" },
  { ticker: "105560", name: "KB Financial Group" },
  { ticker: "000270", name: "Kia" },
  { ticker: "051910", name: "LG Chem" },
  { ticker: "035720", name: "Kakao" },
  { ticker: "035420", name: "NAVER" },
  { ticker: "005490", name: "Posco Holdings" },
  { ticker: "017670", name: "SK Telecom" },
  { ticker: "030200", name: "KT Corporation" },
  { ticker: "096770", name: "SK Innovation" },
  { ticker: "066570", name: "LG Electronics" },
  { ticker: "032830", name: "Samsung Life Insurance" },
  { ticker: "033780", name: "KT&G" },
  { ticker: "055550", name: "Shinhan Financial Group" },
  { ticker: "086790", name: "Hana Financial Group" },
  { ticker: "010950", name: "S-Oil" },
  { ticker: "015760", name: "Korea Electric Power (KEPCO)" },
  { ticker: "012330", name: "Hyundai Mobis" },
  { ticker: "003550", name: "LG" },
  { ticker: "028260", name: "Samsung C&T" },
  { ticker: "009150", name: "Samsung Electro-Mechanics" },
  { ticker: "009540", name: "HD Korea Shipbuilding" },
  { ticker: "042660", name: "Hanwha Ocean" },
  { ticker: "034730", name: "SK" },
];

// ── Nifty 50 ───────────────────────────────────────────────────────────────
const NIFTY_50: StockOption[] = [
  { ticker: "RELIANCE",    name: "Reliance Industries" },
  { ticker: "TCS",         name: "Tata Consultancy Services" },
  { ticker: "HDFCBANK",    name: "HDFC Bank" },
  { ticker: "ICICIBANK",   name: "ICICI Bank" },
  { ticker: "INFY",        name: "Infosys" },
  { ticker: "HINDUNILVR",  name: "Hindustan Unilever" },
  { ticker: "ITC",         name: "ITC" },
  { ticker: "KOTAKBANK",   name: "Kotak Mahindra Bank" },
  { ticker: "AXISBANK",    name: "Axis Bank" },
  { ticker: "SBIN",        name: "State Bank of India" },
  { ticker: "BAJFINANCE",  name: "Bajaj Finance" },
  { ticker: "ASIANPAINT",  name: "Asian Paints" },
  { ticker: "MARUTI",      name: "Maruti Suzuki" },
  { ticker: "HCLTECH",     name: "HCL Technologies" },
  { ticker: "WIPRO",       name: "Wipro" },
  { ticker: "BAJAJFINSV",  name: "Bajaj Finserv" },
  { ticker: "TECHM",       name: "Tech Mahindra" },
  { ticker: "TITAN",       name: "Titan Company" },
  { ticker: "ULTRACEMCO",  name: "UltraTech Cement" },
  { ticker: "NESTLEIND",   name: "Nestle India" },
  { ticker: "NTPC",        name: "NTPC" },
  { ticker: "POWERGRID",   name: "Power Grid Corp" },
  { ticker: "COALINDIA",   name: "Coal India" },
  { ticker: "TATAMOTORS",  name: "Tata Motors" },
  { ticker: "DRREDDY",     name: "Dr. Reddy's Laboratories" },
  { ticker: "CIPLA",       name: "Cipla" },
  { ticker: "TATASTEEL",   name: "Tata Steel" },
  { ticker: "SUNPHARMA",   name: "Sun Pharma" },
  { ticker: "BRITANNIA",   name: "Britannia Industries" },
  { ticker: "BPCL",        name: "BPCL" },
  { ticker: "HINDALCO",    name: "Hindalco Industries" },
  { ticker: "INDUSINDBK",  name: "IndusInd Bank" },
  { ticker: "GRASIM",      name: "Grasim Industries" },
  { ticker: "HEROMOTOCO",  name: "Hero MotoCorp" },
  { ticker: "APOLLOHOSP",  name: "Apollo Hospitals" },
  { ticker: "DIVISLAB",    name: "Divi's Laboratories" },
  { ticker: "JSWSTEEL",    name: "JSW Steel" },
  { ticker: "TATACONSUMM", name: "Tata Consumer Products" },
  { ticker: "EICHERMOT",   name: "Eicher Motors" },
  { ticker: "ONGC",        name: "ONGC" },
  { ticker: "LT",          name: "Larsen & Toubro" },
  { ticker: "BHARTIARTL",  name: "Bharti Airtel" },
  { ticker: "HDFCLIFE",    name: "HDFC Life Insurance" },
  { ticker: "ADANIENT",    name: "Adani Enterprises" },
  { ticker: "ADANIPORTS",  name: "Adani Ports" },
  { ticker: "LTIM",        name: "LTIMindtree" },
  { ticker: "UPL",         name: "UPL" },
  { ticker: "TRENT",       name: "Trent" },
  { ticker: "BEL",         name: "Bharat Electronics" },
  { ticker: "SHRIRAMFIN",  name: "Shriram Finance" },
];

// ── ASX 200 ────────────────────────────────────────────────────────────────
const ASX_TOP: StockOption[] = [
  { ticker: "BHP",    name: "BHP Group" },
  { ticker: "CBA",    name: "Commonwealth Bank" },
  { ticker: "CSL",    name: "CSL" },
  { ticker: "ANZ",    name: "ANZ Bank" },
  { ticker: "NAB",    name: "National Australia Bank" },
  { ticker: "WBC",    name: "Westpac Banking" },
  { ticker: "MQG",    name: "Macquarie Group" },
  { ticker: "WOW",    name: "Woolworths Group" },
  { ticker: "WES",    name: "Wesfarmers" },
  { ticker: "TLS",    name: "Telstra" },
  { ticker: "RIO",    name: "Rio Tinto" },
  { ticker: "FMG",    name: "Fortescue" },
  { ticker: "S32",    name: "South32" },
  { ticker: "XRO",    name: "Xero" },
  { ticker: "COH",    name: "Cochlear" },
  { ticker: "ALL",    name: "Aristocrat Leisure" },
  { ticker: "ASX",    name: "ASX" },
  { ticker: "TCL",    name: "Transurban" },
  { ticker: "QAN",    name: "Qantas Airways" },
  { ticker: "STO",    name: "Santos" },
  { ticker: "WDS",    name: "Woodside Energy" },
  { ticker: "ORG",    name: "Origin Energy" },
  { ticker: "IAG",    name: "Insurance Australia Group" },
  { ticker: "SUN",    name: "Suncorp Group" },
  { ticker: "QBE",    name: "QBE Insurance" },
  { ticker: "RMD",    name: "ResMed" },
  { ticker: "REA",    name: "REA Group" },
  { ticker: "SEK",    name: "Seek" },
  { ticker: "TWE",    name: "Treasury Wine Estates" },
  { ticker: "ALD",    name: "Ampol" },
  { ticker: "APA",    name: "APA Group" },
  { ticker: "JHX",    name: "James Hardie Industries" },
  { ticker: "ORI",    name: "Orica" },
  { ticker: "GMG",    name: "Goodman Group" },
  { ticker: "AMC",    name: "Amcor" },
];

// ── S&P/TSX 60 ─────────────────────────────────────────────────────────────
const TSX_TOP: StockOption[] = [
  { ticker: "RY",     name: "Royal Bank of Canada" },
  { ticker: "TD",     name: "Toronto-Dominion Bank" },
  { ticker: "SHOP",   name: "Shopify" },
  { ticker: "ENB",    name: "Enbridge" },
  { ticker: "CNQ",    name: "Canadian Natural Resources" },
  { ticker: "TRP",    name: "TC Energy" },
  { ticker: "BCE",    name: "BCE" },
  { ticker: "BNS",    name: "Bank of Nova Scotia" },
  { ticker: "BMO",    name: "Bank of Montreal" },
  { ticker: "CM",     name: "CIBC" },
  { ticker: "ABX",    name: "Barrick Gold" },
  { ticker: "AEM",    name: "Agnico Eagle Mines" },
  { ticker: "CVE",    name: "Cenovus Energy" },
  { ticker: "SU",     name: "Suncor Energy" },
  { ticker: "IMO",    name: "Imperial Oil" },
  { ticker: "MFC",    name: "Manulife Financial" },
  { ticker: "SLF",    name: "Sun Life Financial" },
  { ticker: "GWO",    name: "Great-West Lifeco" },
  { ticker: "L",      name: "Loblaw Companies" },
  { ticker: "WN",     name: "George Weston" },
  { ticker: "MRU",    name: "Metro" },
  { ticker: "CNR",    name: "Canadian National Railway" },
  { ticker: "CP",     name: "Canadian Pacific Kansas City" },
  { ticker: "WCN",    name: "Waste Connections" },
  { ticker: "BAM",    name: "Brookfield Asset Management" },
  { ticker: "FTS",    name: "Fortis" },
  { ticker: "H",      name: "Hydro One" },
  { ticker: "EMA",    name: "Emera" },
  { ticker: "PPL",    name: "Pembina Pipeline" },
  { ticker: "FFH",    name: "Fairfax Financial" },
  { ticker: "SAP",    name: "Saputo" },
  { ticker: "PKI",    name: "Parkland" },
  { ticker: "DOL",    name: "Dollarama" },
  { ticker: "ATD",    name: "Alimentation Couche-Tard" },
  { ticker: "T",      name: "TELUS" },
];

// ── Bovespa ────────────────────────────────────────────────────────────────
const BOVESPA_TOP: StockOption[] = [
  { ticker: "PETR4",  name: "Petrobras PN" },
  { ticker: "PETR3",  name: "Petrobras ON" },
  { ticker: "VALE3",  name: "Vale ON" },
  { ticker: "ITUB4",  name: "Itaú Unibanco PN" },
  { ticker: "BBDC4",  name: "Bradesco PN" },
  { ticker: "B3SA3",  name: "B3" },
  { ticker: "EMBR3",  name: "Embraer" },
  { ticker: "SUZB3",  name: "Suzano" },
  { ticker: "WEGE3",  name: "WEG" },
  { ticker: "RENT3",  name: "Localiza" },
  { ticker: "ABEV3",  name: "Ambev" },
  { ticker: "LREN3",  name: "Lojas Renner" },
  { ticker: "TOTS3",  name: "TOTVS" },
  { ticker: "BBAS3",  name: "Banco do Brasil" },
  { ticker: "NTCO3",  name: "Natura & Co" },
  { ticker: "HYPE3",  name: "Hypera Pharma" },
  { ticker: "MGLU3",  name: "Magazine Luiza" },
  { ticker: "ELET3",  name: "Eletrobras ON" },
  { ticker: "CMIG4",  name: "Cemig PN" },
  { ticker: "CPLE6",  name: "Copel PNB" },
  { ticker: "VIVT3",  name: "Telefonica Brasil" },
  { ticker: "TIMS3",  name: "TIM" },
  { ticker: "JBSS3",  name: "JBS" },
  { ticker: "BRFS3",  name: "BRF" },
  { ticker: "PRIO3",  name: "Prio (PetroRio)" },
  { ticker: "SMTO3",  name: "São Martinho" },
  { ticker: "GGBR4",  name: "Gerdau PN" },
  { ticker: "USIM5",  name: "Usiminas PNA" },
  { ticker: "RADL3",  name: "Raia Drogasil" },
  { ticker: "MULT3",  name: "Multiplan" },
];

// ── SMI (Swiss Market Index) ───────────────────────────────────────────────
const SMI_20: StockOption[] = [
  { ticker: "NESN",   name: "Nestlé" },
  { ticker: "NOVN",   name: "Novartis" },
  { ticker: "ROG",    name: "Roche Holding" },
  { ticker: "ABBN",   name: "ABB" },
  { ticker: "ZURN",   name: "Zurich Insurance Group" },
  { ticker: "SREN",   name: "Swiss Re" },
  { ticker: "UBSG",   name: "UBS Group" },
  { ticker: "CFR",    name: "Compagnie Financière Richemont" },
  { ticker: "LONN",   name: "Lonza Group" },
  { ticker: "GIVN",   name: "Givaudan" },
  { ticker: "HOLN",   name: "Holcim" },
  { ticker: "PGHN",   name: "Partners Group" },
  { ticker: "GEBN",   name: "Geberit" },
  { ticker: "KNIN",   name: "Kuehne+Nagel" },
  { ticker: "SIKA",   name: "Sika" },
  { ticker: "SOON",   name: "Sonova" },
  { ticker: "SGSN",   name: "SGS" },
  { ticker: "SCMN",   name: "Swisscom" },
  { ticker: "SLHN",   name: "Swiss Life" },
  { ticker: "BAER",   name: "Julius Bär" },
];

// ── AEX (Amsterdam) ────────────────────────────────────────────────────────
const AEX_25: StockOption[] = [
  { ticker: "ASML",   name: "ASML Holding" },
  { ticker: "ADYEN",  name: "Adyen" },
  { ticker: "STLAM",  name: "Stellantis" },
  { ticker: "INGA",   name: "ING Groep" },
  { ticker: "WKL",    name: "Wolters Kluwer" },
  { ticker: "UMG",    name: "Universal Music Group" },
  { ticker: "HEIA",   name: "Heineken" },
  { ticker: "AD",     name: "Ahold Delhaize" },
  { ticker: "PHIA",   name: "Philips" },
  { ticker: "NN",     name: "NN Group" },
  { ticker: "PRX",    name: "Prosus" },
  { ticker: "MT",     name: "ArcelorMittal" },
  { ticker: "RAND",   name: "Randstad" },
  { ticker: "ABN",    name: "ABN AMRO" },
  { ticker: "BESI",   name: "BE Semiconductor Industries" },
  { ticker: "IMCD",   name: "IMCD Group" },
  { ticker: "AGN",    name: "Aegon" },
  { ticker: "TKWY",   name: "Just Eat Takeaway" },
  { ticker: "EXOR",   name: "Exor" },
  { ticker: "OCI",    name: "OCI" },
  { ticker: "CRBN",   name: "Corbion" },
  { ticker: "PNL",    name: "PostNL" },
  { ticker: "SHELL",  name: "Shell" },
  { ticker: "FLOW",   name: "Flow Traders" },
  { ticker: "NXPI",   name: "NXP Semiconductors" },
];

// ── IBEX 35 ────────────────────────────────────────────────────────────────
const IBEX_35: StockOption[] = [
  { ticker: "SAN",    name: "Banco Santander" },
  { ticker: "BBVA",   name: "BBVA" },
  { ticker: "IBE",    name: "Iberdrola" },
  { ticker: "ITX",    name: "Inditex" },
  { ticker: "REP",    name: "Repsol" },
  { ticker: "TEF",    name: "Telefónica" },
  { ticker: "ACS",    name: "ACS Group" },
  { ticker: "CABK",   name: "CaixaBank" },
  { ticker: "CLNX",   name: "Cellnex Telecom" },
  { ticker: "AMS",    name: "Amadeus IT Group" },
  { ticker: "GRF",    name: "Grifols" },
  { ticker: "REE",    name: "Redeia (Red Eléctrica)" },
  { ticker: "ELE",    name: "Endesa" },
  { ticker: "FER",    name: "Ferrovial" },
  { ticker: "ANA",    name: "Acciona" },
  { ticker: "NTGY",   name: "Naturgy" },
  { ticker: "MTS",    name: "ArcelorMittal" },
  { ticker: "IAG",    name: "IAG (International Airlines)" },
  { ticker: "BKT",    name: "Bankinter" },
  { ticker: "MAP",    name: "Mapfre" },
  { ticker: "FDR",    name: "Fluidra" },
  { ticker: "SLR",    name: "Solaria Energía" },
  { ticker: "ENG",    name: "Enagas" },
  { ticker: "SCYR",   name: "Sacyr" },
  { ticker: "MRL",    name: "Merlin Properties" },
  { ticker: "UNI",    name: "Unicaja Banco" },
  { ticker: "ROVI",   name: "Laboratorio Rovi" },
  { ticker: "COL",    name: "Inmobiliaria Colonial" },
  { ticker: "LOG",    name: "Logista" },
  { ticker: "AENA",   name: "AENA" },
  { ticker: "MEL",    name: "Meliá Hotels International" },
  { ticker: "ACX",    name: "Acerinox" },
  { ticker: "IDR",    name: "Indra Sistemas" },
  { ticker: "SAB",    name: "Banco Sabadell" },
  { ticker: "PUIG",   name: "Puig Brands" },
];

// ── FTSE MIB ───────────────────────────────────────────────────────────────
const FTSE_MIB: StockOption[] = [
  { ticker: "ENI",    name: "ENI" },
  { ticker: "STLAM",  name: "Stellantis" },
  { ticker: "ENEL",   name: "Enel" },
  { ticker: "ISP",    name: "Intesa Sanpaolo" },
  { ticker: "UCG",    name: "UniCredit" },
  { ticker: "RACE",   name: "Ferrari" },
  { ticker: "G",      name: "Assicurazioni Generali" },
  { ticker: "PRY",    name: "Prysmian" },
  { ticker: "MONC",   name: "Moncler" },
  { ticker: "STM",    name: "STMicroelectronics" },
  { ticker: "TEN",    name: "Tenaris" },
  { ticker: "LDO",    name: "Leonardo" },
  { ticker: "MB",     name: "Mediobanca" },
  { ticker: "CNH",    name: "CNH Industrial" },
  { ticker: "PIRC",   name: "Pirelli & C." },
  { ticker: "CPR",    name: "Campari" },
  { ticker: "AMP",    name: "Amplifon" },
  { ticker: "REC",    name: "Recordati" },
  { ticker: "TRN",    name: "Terna" },
  { ticker: "SRG",    name: "Snam" },
  { ticker: "NEXI",   name: "Nexi" },
  { ticker: "BZU",    name: "Buzzi" },
  { ticker: "BC",     name: "Brunello Cucinelli" },
  { ticker: "HER",    name: "Hera" },
  { ticker: "DIA",    name: "DiaSorin" },
  { ticker: "PST",    name: "Poste Italiane" },
  { ticker: "REY",    name: "Reply" },
  { ticker: "BPES",   name: "BPER Banca" },
  { ticker: "SPM",    name: "Saipem" },
  { ticker: "BMPS",   name: "Banca Monte dei Paschi" },
];

// ── OMX Stockholm ──────────────────────────────────────────────────────────
const OMX_STOCKHOLM: StockOption[] = [
  { ticker: "NDA-SE", name: "Nordea" },
  { ticker: "ATCO-A", name: "Atlas Copco (A)" },
  { ticker: "ERIC-B", name: "Ericsson (B)" },
  { ticker: "VOLV-B", name: "Volvo (B)" },
  { ticker: "INVE-B", name: "Investor AB (B)" },
  { ticker: "SAND",   name: "Sandvik" },
  { ticker: "ESSITY-B", name: "Essity (B)" },
  { ticker: "HM-B",   name: "H&M (B)" },
  { ticker: "HEXA-B", name: "Hexagon (B)" },
  { ticker: "SKF-B",  name: "SKF (B)" },
  { ticker: "BOL",    name: "Boliden" },
  { ticker: "SECU-B", name: "Securitas (B)" },
  { ticker: "SEB-A",  name: "SEB (A)" },
  { ticker: "SHB-A",  name: "Svenska Handelsbanken (A)" },
  { ticker: "SWED-A", name: "Swedbank (A)" },
  { ticker: "ICA",    name: "ICA Gruppen" },
  { ticker: "EPIA",   name: "Epiroc (A)" },
  { ticker: "SSAB-A", name: "SSAB (A)" },
  { ticker: "TEL2-B", name: "Tele2 (B)" },
  { ticker: "ALFA",   name: "Alfa Laval" },
  { ticker: "ASSA-B", name: "ASSA ABLOY (B)" },
  { ticker: "SAAB-B", name: "Saab (B)" },
  { ticker: "AZN",    name: "AstraZeneca" },
  { ticker: "KINV-B", name: "Kinnevik (B)" },
  { ticker: "CAST",   name: "Castellum" },
];

// ── TASI (Saudi Tadawul) ───────────────────────────────────────────────────
const TASI_TOP: StockOption[] = [
  { ticker: "2222",   name: "Saudi Aramco" },
  { ticker: "1120",   name: "Al Rajhi Bank" },
  { ticker: "1180",   name: "Saudi National Bank (SNB)" },
  { ticker: "2010",   name: "SABIC" },
  { ticker: "7010",   name: "Saudi Telecom (STC)" },
  { ticker: "2280",   name: "Almarai" },
  { ticker: "1010",   name: "Riyad Bank" },
  { ticker: "1050",   name: "Banque Saudi Fransi" },
  { ticker: "1150",   name: "Alinma Bank" },
  { ticker: "4020",   name: "Ma'aden (Saudi Mining)" },
  { ticker: "2350",   name: "Saudi Kayan Petrochemical" },
  { ticker: "4030",   name: "Saudi Electricity Company" },
  { ticker: "7020",   name: "Mobily (Etihad Etisalat)" },
  { ticker: "4260",   name: "Jarir Marketing" },
  { ticker: "2020",   name: "SABIC Agri-Nutrients" },
  { ticker: "2060",   name: "Yanbu Petrochemicals (Yansab)" },
  { ticker: "1060",   name: "Saudi Arabia Co-op Insurance" },
  { ticker: "1080",   name: "Arab National Bank" },
  { ticker: "4001",   name: "Saudi Tadawul Group" },
  { ticker: "2300",   name: "Saudi Fertilizers (Safco)" },
  { ticker: "4040",   name: "Luberef (Aramco Base Oil)" },
  { ticker: "4323",   name: "Abdullah Al Othaim Markets" },
  { ticker: "2330",   name: "Advanced Petrochemical" },
  { ticker: "2360",   name: "Petro Rabigh" },
  { ticker: "4140",   name: "Mouwasat Medical Services" },
];

// ── TAIEX (Taiwan) ─────────────────────────────────────────────────────────
const TAIEX_TOP: StockOption[] = [
  { ticker: "2330",   name: "TSMC (台積電)" },
  { ticker: "2317",   name: "Hon Hai / Foxconn (鴻海)" },
  { ticker: "2454",   name: "MediaTek (聯發科)" },
  { ticker: "2382",   name: "Quanta Computer (廣達)" },
  { ticker: "2308",   name: "Delta Electronics (台達電)" },
  { ticker: "2303",   name: "UMC (聯電)" },
  { ticker: "2412",   name: "Chunghwa Telecom (中華電信)" },
  { ticker: "2881",   name: "Fubon Financial (富邦金控)" },
  { ticker: "2882",   name: "Cathay Financial (國泰金控)" },
  { ticker: "2886",   name: "Mega Financial (兆豐金控)" },
  { ticker: "2891",   name: "CTBC Financial (中信金控)" },
  { ticker: "2002",   name: "China Steel (中鋼)" },
  { ticker: "1303",   name: "Nan Ya Plastics (南亞塑膠)" },
  { ticker: "1301",   name: "Formosa Plastics (台塑)" },
  { ticker: "1326",   name: "Formosa Chemical (台化)" },
  { ticker: "3711",   name: "ASE Technology (日月光)" },
  { ticker: "2609",   name: "Yang Ming Marine (陽明)" },
  { ticker: "2603",   name: "Evergreen Marine (長榮)" },
  { ticker: "2892",   name: "First Financial (第一金控)" },
  { ticker: "2884",   name: "E.SUN Financial (玉山金控)" },
  { ticker: "3008",   name: "LARGAN Precision (大立光)" },
  { ticker: "2379",   name: "Realtek Semiconductor (瑞昱)" },
  { ticker: "2395",   name: "Advantech (研華)" },
  { ticker: "6505",   name: "Formosa Petrochemical (台塑石化)" },
  { ticker: "2357",   name: "ASUS (華碩)" },
];

// ── WIG 20 (Poland) ────────────────────────────────────────────────────────
const WIG_20: StockOption[] = [
  { ticker: "PKN",    name: "PKN Orlen" },
  { ticker: "PKO",    name: "PKO Bank Polski" },
  { ticker: "PZU",    name: "PZU Group" },
  { ticker: "DNP",    name: "Dino Polska" },
  { ticker: "CDR",    name: "CD Projekt" },
  { ticker: "KGH",    name: "KGHM Polska Miedź" },
  { ticker: "CPS",    name: "Cyfrowy Polsat" },
  { ticker: "LPP",    name: "LPP" },
  { ticker: "ALE",    name: "Allegro" },
  { ticker: "MBK",    name: "mBank" },
  { ticker: "PEO",    name: "Bank Pekao" },
  { ticker: "SPL",    name: "Santander Bank Polska" },
  { ticker: "OPL",    name: "Orange Polska" },
  { ticker: "BDX",    name: "Budimex" },
  { ticker: "JSW",    name: "JSW (Jastrzębska Spółka)" },
  { ticker: "TPE",    name: "Tauron Polska Energia" },
  { ticker: "XTB",    name: "XTB" },
  { ticker: "GPW",    name: "GPW (Warsaw Stock Exchange)" },
  { ticker: "ENA",    name: "Enea" },
  { ticker: "ACP",    name: "Asseco Poland" },
];

// ── ATX (Austria) ──────────────────────────────────────────────────────────
const ATX_20: StockOption[] = [
  { ticker: "OMV",    name: "OMV" },
  { ticker: "EBS",    name: "Erste Group Bank" },
  { ticker: "RBI",    name: "Raiffeisen Bank International" },
  { ticker: "VOE",    name: "voestalpine" },
  { ticker: "VIG",    name: "Vienna Insurance Group" },
  { ticker: "ANL",    name: "Andritz" },
  { ticker: "BAWG",   name: "BAWAG Group" },
  { ticker: "CAI",    name: "CA Immobilien Anlagen" },
  { ticker: "NOEJ",   name: "Österreichische Post" },
  { ticker: "EVN",    name: "EVN (Energie Versorgung)" },
  { ticker: "WBSV",   name: "Wienerberger" },
  { ticker: "STR",    name: "Strabag" },
  { ticker: "SBO",    name: "Schoeller-Bleckmann" },
  { ticker: "LNZF",   name: "Lenzing" },
  { ticker: "FACC",   name: "FACC" },
  { ticker: "IMMO",   name: "Immofinanz" },
  { ticker: "UBM",    name: "UBM Development" },
  { ticker: "KTMI",   name: "KTM Industries" },
  { ticker: "TKA",    name: "Telekom Austria" },
  { ticker: "RHI",    name: "RHI Magnesita" },
];

// ── Straits Times Index (Singapore) ────────────────────────────────────────
const STI_TOP: StockOption[] = [
  { ticker: "D05",    name: "DBS Group" },
  { ticker: "O39",    name: "OCBC Bank" },
  { ticker: "U11",    name: "United Overseas Bank (UOB)" },
  { ticker: "Z74",    name: "Singapore Telecom (Singtel)" },
  { ticker: "C6L",    name: "Singapore Airlines" },
  { ticker: "S68",    name: "Singapore Exchange (SGX)" },
  { ticker: "F34",    name: "Wilmar International" },
  { ticker: "N2IU",   name: "Mapletree Industrial Trust" },
  { ticker: "ME8U",   name: "Mapletree Logistics Trust" },
  { ticker: "A17U",   name: "CapitaLand Integrated Comm Trust" },
  { ticker: "C38U",   name: "CapitaLand Ascendas REIT" },
  { ticker: "9CI",    name: "CapitaLand Investment" },
  { ticker: "G13",    name: "Genting Singapore" },
  { ticker: "V03",    name: "Venture Corporation" },
  { ticker: "BN4",    name: "Keppel" },
  { ticker: "S63",    name: "ST Engineering" },
  { ticker: "AWX",    name: "Asian Pay Television Trust" },
  { ticker: "U96",    name: "Sembcorp Industries" },
  { ticker: "BS6",    name: "Yangzijiang Shipbuilding" },
  { ticker: "Y92",    name: "Thai Beverage" },
];

export const STOCK_INDICES: StockIndex[] = [
  // ── Türkiye ──────────────────────────────────────────────────────────────
  { id: "BIST100",   label: "BIST 100",          country: "Türkiye",    flag: "🇹🇷", exchangeSuffix: ".IS",  currency: "TRY",  stocks: BIST_STOCKS   },
  { id: "BIST30",    label: "BIST 30",            country: "Türkiye",    flag: "🇹🇷", exchangeSuffix: ".IS",  currency: "TRY",  stocks: BIST_30       },
  // ── Amerika Birleşik Devletleri ──────────────────────────────────────────
  { id: "NASDAQ100", label: "NASDAQ 100",         country: "ABD",        flag: "🇺🇸", exchangeSuffix: "",     currency: "USD",  stocks: NASDAQ_100    },
  { id: "SP500",     label: "S&P 500",            country: "ABD",        flag: "🇺🇸", exchangeSuffix: "",     currency: "USD",  stocks: SP500_TOP     },
  { id: "DOW30",     label: "Dow Jones 30",       country: "ABD",        flag: "🇺🇸", exchangeSuffix: "",     currency: "USD",  stocks: DOW_30        },
  // ── Avrupa ───────────────────────────────────────────────────────────────
  { id: "DAX40",     label: "DAX 40",             country: "Almanya",    flag: "🇩🇪", exchangeSuffix: ".DE",  currency: "EUR",  stocks: DAX_40        },
  { id: "FTSE100",   label: "FTSE 100",           country: "İngiltere",  flag: "🇬🇧", exchangeSuffix: ".L",   currency: "GBP",  priceDivisor: 100, stocks: FTSE_100 },
  { id: "CAC40",     label: "CAC 40",             country: "Fransa",     flag: "🇫🇷", exchangeSuffix: ".PA",  currency: "EUR",  stocks: CAC_40        },
  { id: "SMI",       label: "SMI 20",             country: "İsviçre",    flag: "🇨🇭", exchangeSuffix: ".SW",  currency: "CHF",  stocks: SMI_20        },
  { id: "AEX",       label: "AEX 25",             country: "Hollanda",   flag: "🇳🇱", exchangeSuffix: ".AS",  currency: "EUR",  stocks: AEX_25        },
  { id: "IBEX35",    label: "IBEX 35",            country: "İspanya",    flag: "🇪🇸", exchangeSuffix: ".MC",  currency: "EUR",  stocks: IBEX_35       },
  { id: "FTSEMIB",   label: "FTSE MIB",           country: "İtalya",     flag: "🇮🇹", exchangeSuffix: ".MI",  currency: "EUR",  stocks: FTSE_MIB      },
  { id: "OMXS",      label: "OMX Stockholm",      country: "İsveç",      flag: "🇸🇪", exchangeSuffix: ".ST",  currency: "SEK",  stocks: OMX_STOCKHOLM },
  { id: "WIG20",     label: "WIG 20",             country: "Polonya",    flag: "🇵🇱", exchangeSuffix: ".WA",  currency: "PLN",  stocks: WIG_20        },
  { id: "ATX",       label: "ATX",                country: "Avusturya",  flag: "🇦🇹", exchangeSuffix: ".VI",  currency: "EUR",  stocks: ATX_20        },
  // ── Asya-Pasifik ─────────────────────────────────────────────────────────
  { id: "NIKKEI225", label: "Nikkei 225",         country: "Japonya",    flag: "🇯🇵", exchangeSuffix: ".T",   currency: "JPY",  stocks: NIKKEI_TOP    },
  { id: "HANGSENG",  label: "Hang Seng",          country: "Hong Kong",  flag: "🇭🇰", exchangeSuffix: ".HK",  currency: "HKD",  stocks: HANG_SENG     },
  { id: "KOSPI",     label: "KOSPI",              country: "G. Kore",    flag: "🇰🇷", exchangeSuffix: ".KS",  currency: "KRW",  stocks: KOSPI_TOP     },
  { id: "NIFTY50",   label: "Nifty 50",           country: "Hindistan",  flag: "🇮🇳", exchangeSuffix: ".NS",  currency: "INR",  stocks: NIFTY_50      },
  { id: "ASX200",    label: "ASX 200",            country: "Avustralya", flag: "🇦🇺", exchangeSuffix: ".AX",  currency: "AUD",  stocks: ASX_TOP       },
  { id: "TAIEX",     label: "TAIEX",              country: "Tayvan",     flag: "🇹🇼", exchangeSuffix: ".TW",  currency: "TWD",  stocks: TAIEX_TOP     },
  { id: "STI",       label: "Straits Times Index",country: "Singapur",   flag: "🇸🇬", exchangeSuffix: ".SI",  currency: "SGD",  stocks: STI_TOP       },
  // ── Amerika (Diğer) ──────────────────────────────────────────────────────
  { id: "TSX60",     label: "S&P/TSX 60",         country: "Kanada",     flag: "🇨🇦", exchangeSuffix: ".TO",  currency: "CAD",  stocks: TSX_TOP       },
  { id: "BOVESPA",   label: "Bovespa",            country: "Brezilya",   flag: "🇧🇷", exchangeSuffix: ".SA",  currency: "BRL",  stocks: BOVESPA_TOP   },
  // ── Orta Doğu ────────────────────────────────────────────────────────────
  { id: "TASI",      label: "TASI (Tadawul)",     country: "S. Arabistan",flag: "🇸🇦", exchangeSuffix: ".SR",  currency: "SAR",  stocks: TASI_TOP      },
];
