export interface ImalatPoz {
  code: string;
  category: string;
  name: string;
  unit: string;
  description?: string;
}

export const IMALAT_POZ_KATEGORILERI = [
  "Hafriyat ve Toprak",
  "Beton ve Demir",
  "Kalıp",
  "Duvar",
  "Sıva ve Şap",
  "Yalıtım",
  "Çatı",
  "Kaplama",
  "Boya",
  "Doğrama",
  "Sıhhi Tesisat",
  "Elektrik",
  "Mekanik Tesisat",
  "Asansör",
  "Cephe",
  "Çevre Düzenleme",
  "Yıkım ve Söküm",
  "Diğer",
] as const;

export const DEFAULT_IMALAT_POZLARI: ImalatPoz[] = [
  // ====== HAFRİYAT VE TOPRAK ======
  { code: "14.001", category: "Hafriyat ve Toprak", name: "El ile yumuşak ve sert toprak kazısı", unit: "m³", description: "Her derinlik ve genişlikte el ile kazı yapılması.\nKazılan malzemenin kazı kenarına atılması veya 4 m mesafeye kadar taşınması dahildir.\nKazı yan duvarlarının iksası hariçtir." },
  { code: "14.002", category: "Hafriyat ve Toprak", name: "Makine ile yumuşak toprak kazısı", unit: "m³", description: "Ekskavatör veya yükleyici ile her derinlik ve genişlikte kazı.\nKazılan malzemenin yükleme yapılarak en fazla 25 m mesafeye taşınması dahildir." },
  { code: "14.003", category: "Hafriyat ve Toprak", name: "Makine ile sert toprak kazısı", unit: "m³", description: "Ekskavatör/kırıcı ile sert ve taşlı zeminlerde kazı yapılması.\nGerekirse hidrolik kırıcı kullanımı dahildir." },
  { code: "14.005", category: "Hafriyat ve Toprak", name: "Makine ile yumuşak küskülük kazı", unit: "m³" },
  { code: "14.006", category: "Hafriyat ve Toprak", name: "Makine ile sert küskülük kazı", unit: "m³" },
  { code: "14.007", category: "Hafriyat ve Toprak", name: "Makine ile yumuşak kaya kazısı", unit: "m³" },
  { code: "14.008", category: "Hafriyat ve Toprak", name: "Makine ile sert kaya kazısı", unit: "m³", description: "Patlayıcı veya hidrolik kırıcı ile sert kaya formasyonunda kazı.\nKırılan malzemenin yüklenip taşınması dahildir." },
  { code: "14.010", category: "Hafriyat ve Toprak", name: "Dolgu yapılması ve sıkıştırılması", unit: "m³", description: "Uygun malzeme ile 30 cm tabakalar halinde dolgu serilmesi.\nHer tabakanın silindir veya kompaktör ile sıkıştırılması.\nProktor değerinin %95'ine ulaşılması esastır." },
  { code: "14.011", category: "Hafriyat ve Toprak", name: "Stabilize malzeme ile dolgu", unit: "m³" },
  { code: "14.012", category: "Hafriyat ve Toprak", name: "Mıcır ile dolgu yapılması", unit: "m³" },
  { code: "14.020", category: "Hafriyat ve Toprak", name: "Kazı malzemesinin nakli", unit: "m³·km", description: "Kazı veya hafriyat malzemesinin döküm sahasına taşınması.\nNakliye mesafesi km cinsinden hesaplanır." },
  { code: "14.030", category: "Hafriyat ve Toprak", name: "Bohça (palplanş) iksa yapılması", unit: "m²" },
  { code: "14.040", category: "Hafriyat ve Toprak", name: "Ahşap iksa yapılması", unit: "m²" },
  { code: "14.050", category: "Hafriyat ve Toprak", name: "Geosentetik donatılı duvar", unit: "m²" },

  // ====== BETON VE DEMİR ======
  { code: "15.001/1A", category: "Beton ve Demir", name: "C16/20 hazır beton dökümü (donatısız)", unit: "m³", description: "Transmikser ile sahaya getirilen C16/20 hazır betonun pompa veya başka yöntemle yerine dökülmesi.\nVibratörle sıkıştırılması ve kür işlemi dahildir." },
  { code: "15.001/2A", category: "Beton ve Demir", name: "C20/25 hazır beton dökümü", unit: "m³", description: "Beton pompası kullanılarak yerine dökülmesi, vibrasyon ve kür dahildir." },
  { code: "15.001/3A", category: "Beton ve Demir", name: "C25/30 hazır beton dökümü", unit: "m³", description: "Yapısal taşıyıcı elemanlarda kullanılan standart sınıf beton.\nDöküm, sıkıştırma ve kür dahildir." },
  { code: "15.001/4A", category: "Beton ve Demir", name: "C30/37 hazır beton dökümü", unit: "m³" },
  { code: "15.001/5A", category: "Beton ve Demir", name: "C35/45 hazır beton dökümü", unit: "m³" },
  { code: "15.001/6A", category: "Beton ve Demir", name: "C40/50 hazır beton dökümü", unit: "m³" },
  { code: "15.002", category: "Beton ve Demir", name: "Su geçirimsiz (hidrofuge) beton ek bedeli", unit: "m³" },
  { code: "15.003", category: "Beton ve Demir", name: "Liflik beton ek bedeli (çelik/polipropilen)", unit: "m³" },
  { code: "15.010", category: "Beton ve Demir", name: "Grobeton dökümü (C8/10)", unit: "m³", description: "Temel altı tesviye amaçlı 5-10 cm kalınlıkta grobeton.\nÇuvallı çimento veya hazır beton ile yapılır." },
  { code: "15.020", category: "Beton ve Demir", name: "Şap altı tesviye betonu", unit: "m²" },
  { code: "23.014", category: "Beton ve Demir", name: "Çelik hasırın yerine konulması (Q188-Q317)", unit: "ton", description: "Çelik hasırın açılması, kesilmesi, bükülmesi.\nProje yerinde bağlanması ve yerine konulması.\nFire ve atıklar dahil." },
  { code: "23.015", category: "Beton ve Demir", name: "Ø8-Ø12 nervürlü inşaat çeliği", unit: "ton", description: "Demir donatının kesilmesi, bükülmesi.\nKalıba yerleştirilip bağ teli ile bağlanması.\nFire ve bağ teli dahildir." },
  { code: "23.016", category: "Beton ve Demir", name: "Ø14-Ø32 nervürlü inşaat çeliği", unit: "ton", description: "Kolon, kiriş, perde gibi yapısal elemanlarda ana donatı olarak kullanılır.\nKesim, bükme, montaj, bağ teli ve fire dahildir." },
  { code: "23.017", category: "Beton ve Demir", name: "Düz inşaat demiri", unit: "ton" },
  { code: "23.020", category: "Beton ve Demir", name: "Hazır kolon donatı kafesi", unit: "ton" },
  { code: "23.025", category: "Beton ve Demir", name: "Hazır kiriş donatı kafesi", unit: "ton" },
  { code: "23.030", category: "Beton ve Demir", name: "Ankraj çubuğu (paslanmaz)", unit: "ad" },
  { code: "23.040", category: "Beton ve Demir", name: "Epoksi ankraj uygulaması", unit: "ad" },
  { code: "23.050", category: "Beton ve Demir", name: "Mevcut betona kimyasal ankraj", unit: "ad" },

  // ====== KALIP ======
  { code: "21.001", category: "Kalıp", name: "Plywood ile düz yüzeyli betonarme kalıbı", unit: "m²", description: "18 mm su kontrası plywood ile düz yüzeyli kalıp imalatı.\nIskelet ahşap kereste ile, destek ve payandalar dahildir.\nSökülüp tekrar kurulması dahil." },
  { code: "21.002", category: "Kalıp", name: "Plywood ile eğri yüzeyli betonarme kalıbı", unit: "m²" },
  { code: "21.011", category: "Kalıp", name: "Tünel kalıp ile betonarme kalıbı", unit: "m²", description: "Çelik tünel kalıp sistemi ile duvar ve döşemenin tek seferde dökümü.\nKalıp kurulumu, dökum, sökum ve yer değişimi dahildir." },
  { code: "21.020", category: "Kalıp", name: "Çelik kolon/perde kalıbı", unit: "m²" },
  { code: "21.030", category: "Kalıp", name: "Mantar kalıp sistemi", unit: "m²" },
  { code: "21.040", category: "Kalıp", name: "Tırmanır kalıp (climbing)", unit: "m²" },
  { code: "21.050", category: "Kalıp", name: "Tek yüzlü perde kalıbı", unit: "m²" },
  { code: "21.057", category: "Kalıp", name: "Çelik kalıp ile düz yüzey betonarme kalıbı", unit: "m²", description: "Tekrar kullanımlı çelik kalıp ile düzgün yüzey elde edilmesi.\nİskelet, payanda ve aksesuarlar dahildir." },
  { code: "21.060", category: "Kalıp", name: "Asmolen kalıp sistemi", unit: "m²" },
  { code: "21.070", category: "Kalıp", name: "Iskele kurulması (cephe)", unit: "m²", description: "Cephe boyu kurulan dış cephe iskelesi.\nKurulum, kullanım süresi ve sökum dahil." },

  // ====== DUVAR ======
  { code: "16.054", category: "Duvar", name: "Yatay delikli tuğla ile duvar (19x19x13.5)", unit: "m³", description: "TS 4377 standardına uygun yatay delikli tuğla.\nÇimento+kireç harcı ile örülmesi.\nDerz dolgusu dahildir." },
  { code: "16.055", category: "Duvar", name: "Yatay delikli tuğla duvar (19x19x8.5)", unit: "m²" },
  { code: "16.057/1A", category: "Duvar", name: "Gaz beton blok ile duvar (G2/0.50, 25cm)", unit: "m²", description: "Otoklavlanmış gaz beton blok ile duvar örülmesi.\nÖzel yapıştırma harcı kullanılır.\nYatay ve düşey hatıl bağlantıları dahildir." },
  { code: "16.057/2A", category: "Duvar", name: "Gaz beton blok ile duvar (G2/0.50, 20cm)", unit: "m²" },
  { code: "16.057/3A", category: "Duvar", name: "Gaz beton blok ile duvar (G2/0.50, 15cm)", unit: "m²" },
  { code: "16.058", category: "Duvar", name: "Bims briket ile duvar", unit: "m²" },
  { code: "16.059", category: "Duvar", name: "Beton briket ile duvar", unit: "m²" },
  { code: "16.060", category: "Duvar", name: "Alçı bloklu (alçıpan) bölme duvar", unit: "m²", description: "Çelik konstrüksiyon üzerine 12.5 mm alçı levha çift kat.\nİçi taşyünü/cam yünü dolgulu.\nDerz bandı, macun ve yüzey hazırlığı dahildir." },
  { code: "16.061", category: "Duvar", name: "Tuğla bacalık ve baca duvarı", unit: "m" },
  { code: "16.070", category: "Duvar", name: "Hatıl betonu yapılması", unit: "m³" },
  { code: "16.080", category: "Duvar", name: "Lento betonu", unit: "m³" },

  // ====== SIVA VE ŞAP ======
  { code: "27.501", category: "Sıva ve Şap", name: "İç cephe çimento harçlı kaba sıva (2cm)", unit: "m²", description: "İç duvarlara çimento+kum harcı ile 2 cm kaba sıva yapılması.\nAlçı sıva veya seramik kaplama altlığı olarak kullanılır." },
  { code: "27.502", category: "Sıva ve Şap", name: "Dış cephe çimento harçlı kaba sıva", unit: "m²" },
  { code: "27.510", category: "Sıva ve Şap", name: "İnce sıva (perdah) yapılması", unit: "m²" },
  { code: "27.525", category: "Sıva ve Şap", name: "Saten alçı sıva (2-3 mm)", unit: "m²", description: "Düzgün hazırlanmış yüzeye saten alçı uygulanması.\nBoyaya hazır pürüzsüz yüzey elde edilir." },
  { code: "27.581", category: "Sıva ve Şap", name: "Makine ile alçı sıva (1.5 cm)", unit: "m²", description: "Sıva makinesi ile tek katta uygulanan alçı sıva.\nDüzeltme ve perdah dahildir." },
  { code: "27.582", category: "Sıva ve Şap", name: "El ile alçı sıva", unit: "m²" },
  { code: "27.583", category: "Sıva ve Şap", name: "Çimento esaslı tesviye şapı (3-5 cm)", unit: "m²", description: "Beton üzerine eğim ve kot için tesviye amaçlı şap dökülmesi.\nSeramik altlığı olarak kullanılır." },
  { code: "27.584", category: "Sıva ve Şap", name: "Düşük yoğunluklu hafif şap", unit: "m²" },
  { code: "27.585", category: "Sıva ve Şap", name: "Self-leveling (kendiliğinden yayılan) şap", unit: "m²" },
  { code: "27.590", category: "Sıva ve Şap", name: "Brüt beton silinmesi/perdahı", unit: "m²" },

  // ====== YALITIM ======
  { code: "10.300.1051", category: "Yalıtım", name: "Polimer bitümlü membran su yalıtımı (3 mm)", unit: "m²", description: "Plastomer (APP) veya elastomer (SBS) esaslı membran.\nAlttan astar uygulanması, üst üste 10 cm bindirme.\nŞaloma ile kaynak yapılarak uygulanır." },
  { code: "10.300.1052", category: "Yalıtım", name: "Polimer bitümlü membran (4 mm, çift kat)", unit: "m²" },
  { code: "10.300.1100", category: "Yalıtım", name: "Sürme su yalıtım (kristalize çimento esaslı)", unit: "m²" },
  { code: "10.300.1110", category: "Yalıtım", name: "Çift komponentli akrilik su yalıtım", unit: "m²" },
  { code: "10.300.1120", category: "Yalıtım", name: "Bitüm-kauçuk esaslı sıvı membran", unit: "m²" },
  { code: "10.300.4421", category: "Yalıtım", name: "5 cm XPS ısı yalıtım plakası", unit: "m²", description: "Ekstrude polistren köpük (XPS) levha ile ısı yalıtımı.\nÖzel polyurethan yapıştırıcı veya mekanik dübel ile sabitleme.\nYüksek su itici özelliği vardır." },
  { code: "10.300.4422", category: "Yalıtım", name: "3 cm XPS ısı yalıtım plakası", unit: "m²" },
  { code: "10.300.4521", category: "Yalıtım", name: "5 cm taşyünü ısı yalıtım plakası", unit: "m²" },
  { code: "10.300.4522", category: "Yalıtım", name: "5 cm camyünü şilte yalıtımı", unit: "m²" },
  { code: "10.300.4530", category: "Yalıtım", name: "5 cm EPS (strafor) ısı yalıtım plakası", unit: "m²" },
  { code: "10.300.4540", category: "Yalıtım", name: "Çatı arası dökme cam yünü", unit: "m³" },
  { code: "10.300.5010", category: "Yalıtım", name: "Asma tavan ses yalıtımı", unit: "m²" },

  // ====== ÇATI ======
  { code: "27.701", category: "Çatı", name: "Kiremit ile çatı kaplaması", unit: "m²", description: "Marsilya, alaturka veya Akdeniz tipi kiremit ile çatı kaplaması.\nLata, kontra lata ve mahya kiremidi dahildir." },
  { code: "27.705", category: "Çatı", name: "Beton kiremit ile çatı kaplaması", unit: "m²" },
  { code: "27.710", category: "Çatı", name: "Çatı ahşap konstrüksiyonu", unit: "m³" },
  { code: "27.715", category: "Çatı", name: "OSB üzerine shingle kaplaması", unit: "m²", description: "OSB plaka üzerine bitümlü asfalt shingle.\nMahya shingle ve havalandırma elemanları dahildir." },
  { code: "27.720", category: "Çatı", name: "Trapez sac ile çatı kaplaması", unit: "m²" },
  { code: "27.725", category: "Çatı", name: "Sandviç panel çatı kaplaması (5 cm)", unit: "m²" },
  { code: "27.730", category: "Çatı", name: "Galvaniz oluk ve indirme borusu", unit: "m" },
  { code: "27.735", category: "Çatı", name: "PVC oluk ve indirme borusu", unit: "m" },
  { code: "27.740", category: "Çatı", name: "Çatı havalandırma bacası", unit: "ad" },

  // ====== KAPLAMA ======
  { code: "26.005", category: "Kaplama", name: "Seramik yer döşemesi (30x30 - 60x60)", unit: "m²", description: "1. sınıf granit seramik karo ile yer döşemesi.\nÇimento esaslı yapıştırıcı ve derz dolgusu dahildir.\nKöşe ve süpürgelik fayansı hariçtir." },
  { code: "26.010", category: "Kaplama", name: "Seramik duvar kaplaması (banyo/mutfak)", unit: "m²" },
  { code: "26.015", category: "Kaplama", name: "Süpürgelik fayans (10 cm)", unit: "m" },
  { code: "26.020", category: "Kaplama", name: "Porselen karo kaplama (60x120)", unit: "m²" },
  { code: "26.301", category: "Kaplama", name: "Granit/mermer döşeme kaplaması", unit: "m²", description: "Doğal taş plakaların döşenmesi.\nÇimento harcı veya yapıştırıcı ile uygulama.\nDerz dolgusu, parlatma ve cilalama dahildir." },
  { code: "26.310", category: "Kaplama", name: "Mermer denizlik (pencere altı)", unit: "m" },
  { code: "26.320", category: "Kaplama", name: "Mermer basamak ve rıht", unit: "m" },
  { code: "26.401", category: "Kaplama", name: "Laminat parke döşemesi (8 mm)", unit: "m²", description: "AC4-AC5 sınıfı laminat parke.\nAltına şok emici sünger ve nem bariyeri dahildir.\nSüpürgelik hariçtir." },
  { code: "26.410", category: "Kaplama", name: "Masif/lamine parke döşemesi", unit: "m²" },
  { code: "26.420", category: "Kaplama", name: "PVC/LVT karo döşeme", unit: "m²" },
  { code: "26.430", category: "Kaplama", name: "Halıfleks döşemesi", unit: "m²" },
  { code: "26.440", category: "Kaplama", name: "Epoksi yer kaplaması (endüstriyel)", unit: "m²" },
  { code: "26.450", category: "Kaplama", name: "Polyuretan döşeme kaplaması", unit: "m²" },

  // ====== BOYA ======
  { code: "25.100", category: "Boya", name: "Astar boya uygulanması", unit: "m²", description: "Yüzey hazırlığı sonrası tek kat astar.\nBoyanın yüzeye tutunmasını sağlar." },
  { code: "25.116/1A", category: "Boya", name: "İç cephe plastik boya (2 kat)", unit: "m²", description: "Yüzey hazırlığı, macunlama ve zımpara.\nTek kat astar, iki kat plastik boya uygulanması." },
  { code: "25.116/2A", category: "Boya", name: "İç cephe saten boya (2 kat)", unit: "m²", description: "Yüksek silinebilirlik özelliği olan saten finişli iç cephe boyası.\nMacun ve zımpara işleri dahildir." },
  { code: "25.116/3A", category: "Boya", name: "İç cephe ipek mat boya", unit: "m²" },
  { code: "25.120", category: "Boya", name: "Tavanlara plastik boya", unit: "m²" },
  { code: "25.130", category: "Boya", name: "Akrilik macun çekilmesi", unit: "m²" },
  { code: "25.150", category: "Boya", name: "Dış cephe akrilik boya (2 kat)", unit: "m²", description: "Dış mekan dayanımlı, su itici akrilik bazlı boya.\nÖn yüzey hazırlığı, astar ve 2 kat son kat dahildir." },
  { code: "25.160", category: "Boya", name: "Dış cephe silikon esaslı boya", unit: "m²" },
  { code: "25.170", category: "Boya", name: "Dış cephe dekoratif kaplama (mineral sıva)", unit: "m²" },
  { code: "25.200", category: "Boya", name: "Yağlı boya (iki kat)", unit: "m²" },
  { code: "25.210", category: "Boya", name: "Sentetik boya", unit: "m²" },
  { code: "25.220", category: "Boya", name: "Su bazlı vernik (parke/ahşap)", unit: "m²" },
  { code: "25.230", category: "Boya", name: "Demir konstrüksiyon antipas + boya", unit: "m²" },

  // ====== DOĞRAMA ======
  { code: "24.151", category: "Doğrama", name: "PVC pencere doğraması (ısıcam dahil)", unit: "m²", description: "5 odacıklı PVC profil ile pencere imalatı.\n4+16+4 mm low-e ısı camı dahildir.\nPervaz, ispanyolet, kol ve menteşe komple monte." },
  { code: "24.152", category: "Doğrama", name: "PVC kapı doğraması", unit: "m²" },
  { code: "24.158", category: "Doğrama", name: "Alüminyum cephe doğraması", unit: "m²", description: "Isı yalıtımlı (termal kırma) alüminyum profil.\nPanjur, kol, menteşe ve cam dahildir." },
  { code: "24.159", category: "Doğrama", name: "Alüminyum sürme pencere", unit: "m²" },
  { code: "24.160", category: "Doğrama", name: "Alüminyum vitrin/giriş kapısı", unit: "m²" },
  { code: "24.165", category: "Doğrama", name: "Otomatik fotoselli giriş kapısı", unit: "ad" },
  { code: "24.170", category: "Doğrama", name: "Giyotin pencere", unit: "m²" },
  { code: "24.231", category: "Doğrama", name: "Ahşap iç kapı (kasa dahil)", unit: "ad", description: "Lake veya kaplama ahşap iç kapı.\nKasa, pervaz, menteşe, kol ve kilit dahil komple montaj." },
  { code: "24.232", category: "Doğrama", name: "Amerikan panel kapı", unit: "ad" },
  { code: "24.240", category: "Doğrama", name: "Ahşap dış kapı", unit: "ad" },
  { code: "24.245", category: "Doğrama", name: "Çelik dış kapı (daire kapısı)", unit: "ad", description: "İki taraflı çelik plaka, içi taşyünü dolgulu çelik kapı.\nÜç noktadan kilitli, dijital göz ve menteşeli." },
  { code: "24.250", category: "Doğrama", name: "Yangın kapısı (60 dk)", unit: "ad" },
  { code: "24.255", category: "Doğrama", name: "Yangın kapısı (90/120 dk)", unit: "ad" },
  { code: "24.260", category: "Doğrama", name: "Sektoral garaj kapısı (motorlu)", unit: "m²" },
  { code: "24.270", category: "Doğrama", name: "Tente/storperde", unit: "m²" },

  // ====== SIHHİ TESİSAT ======
  { code: "071-101", category: "Sıhhi Tesisat", name: "PPR-C boru ve ek parça (Ø20)", unit: "m", description: "Polipropilen randon copolimer (PPR-C) sıcak/soğuk su borusu.\nFüzyon kaynak ile birleştirme.\nGerekli ek parçalar (T, dirsek, manşon) dahil." },
  { code: "071-105", category: "Sıhhi Tesisat", name: "PPR-C boru ve ek parça (Ø25)", unit: "m" },
  { code: "071-110", category: "Sıhhi Tesisat", name: "PPR-C boru ve ek parça (Ø32)", unit: "m" },
  { code: "071-115", category: "Sıhhi Tesisat", name: "PPR-C boru ve ek parça (Ø40)", unit: "m" },
  { code: "072-201", category: "Sıhhi Tesisat", name: "PVC pis su borusu (Ø100)", unit: "m", description: "Sızdırmaz PVC pis su gider borusu.\nMuf veya yapıştırıcı bağlantılı.\nUygun eğimle döşenmesi dahildir." },
  { code: "072-205", category: "Sıhhi Tesisat", name: "PVC pis su borusu (Ø50)", unit: "m" },
  { code: "072-210", category: "Sıhhi Tesisat", name: "PVC pis su borusu (Ø75)", unit: "m" },
  { code: "072-215", category: "Sıhhi Tesisat", name: "Koruge HDPE pis su borusu (Ø160)", unit: "m" },
  { code: "081-501", category: "Sıhhi Tesisat", name: "Klozet (rezervuar dahil) montajı", unit: "ad", description: "Standart porselen klozet, gömme veya asma tip rezervuar.\nMontaj aksesuarları, esnek hortum ve flanş dahil." },
  { code: "081-510", category: "Sıhhi Tesisat", name: "Asma klozet + gömme rezervuar", unit: "ad" },
  { code: "081-520", category: "Sıhhi Tesisat", name: "Lavabo + ayak/tezgah üstü", unit: "ad" },
  { code: "081-530", category: "Sıhhi Tesisat", name: "Pisuvar (sensörlü/manuel)", unit: "ad" },
  { code: "081-540", category: "Sıhhi Tesisat", name: "Banyo eviyesi (akrilik kabin)", unit: "ad" },
  { code: "081-550", category: "Sıhhi Tesisat", name: "Mutfak eviyesi (paslanmaz çift gözlü)", unit: "ad" },
  { code: "081-560", category: "Sıhhi Tesisat", name: "Lavabo bataryası", unit: "ad" },
  { code: "081-565", category: "Sıhhi Tesisat", name: "Eviye bataryası", unit: "ad" },
  { code: "081-570", category: "Sıhhi Tesisat", name: "Duş bataryası + el duşu", unit: "ad" },
  { code: "081-580", category: "Sıhhi Tesisat", name: "Banyo bataryası (banyo+duş)", unit: "ad" },
  { code: "081-590", category: "Sıhhi Tesisat", name: "Termosifon (boyler) montajı", unit: "ad" },
  { code: "081-600", category: "Sıhhi Tesisat", name: "Şofben/kombi su giriş çıkış bağlantısı", unit: "ad" },

  // ====== ELEKTRİK ======
  { code: "33.100", category: "Elektrik", name: "NYA kablo (3x2.5 mm²) çekilmesi", unit: "m", description: "PVC izoleli bakır iletkenli kablonun spiral boruda çekilmesi.\nKlemens bağlantı dahildir." },
  { code: "33.105", category: "Elektrik", name: "NYA kablo (3x4 mm²) çekilmesi", unit: "m" },
  { code: "33.110", category: "Elektrik", name: "NYM kablo (3x1.5 mm²) çekilmesi", unit: "m" },
  { code: "33.115", category: "Elektrik", name: "NYM kablo (3x2.5 mm²) çekilmesi", unit: "m" },
  { code: "33.120", category: "Elektrik", name: "NYY kablo (4x10 mm²) çekilmesi", unit: "m" },
  { code: "33.125", category: "Elektrik", name: "Veri kablosu (Cat6 UTP) çekilmesi", unit: "m" },
  { code: "33.130", category: "Elektrik", name: "TV/SAT kablosu (RG6) çekilmesi", unit: "m" },
  { code: "33.140", category: "Elektrik", name: "Yangın algılama kablosu (JE-H 2x1.5)", unit: "m" },
  { code: "33.300", category: "Elektrik", name: "Sıva altı priz montajı", unit: "ad", description: "Topraklı, çocuk korumalı priz.\nKasa, kapak ve mekanizma dahil." },
  { code: "33.305", category: "Elektrik", name: "Sıva altı USB'li priz", unit: "ad" },
  { code: "33.310", category: "Elektrik", name: "Sıva altı anahtar montajı (tek/komütatör)", unit: "ad" },
  { code: "33.315", category: "Elektrik", name: "Sıva altı dimer anahtar", unit: "ad" },
  { code: "33.320", category: "Elektrik", name: "Veri/data prizi (Cat6 RJ45)", unit: "ad" },
  { code: "33.330", category: "Elektrik", name: "TV/uydu prizi", unit: "ad" },
  { code: "33.340", category: "Elektrik", name: "Spot armatür montajı (LED)", unit: "ad" },
  { code: "33.345", category: "Elektrik", name: "Avize armatür montajı", unit: "ad" },
  { code: "33.350", category: "Elektrik", name: "Aplik armatür montajı", unit: "ad" },
  { code: "33.360", category: "Elektrik", name: "Acil aydınlatma armatürü (kendinden bataryalı)", unit: "ad" },
  { code: "33.365", category: "Elektrik", name: "Yönlendirme (exit) armatürü", unit: "ad" },
  { code: "33.400", category: "Elektrik", name: "Tablo W otomat sigorta (1P-3P)", unit: "ad" },
  { code: "33.410", category: "Elektrik", name: "Kaçak akım rölesi (30 mA)", unit: "ad" },
  { code: "33.420", category: "Elektrik", name: "Daire elektrik tablosu (komple)", unit: "ad" },
  { code: "33.430", category: "Elektrik", name: "Topraklama bakır levha + bağlantı", unit: "ad" },
  { code: "33.440", category: "Elektrik", name: "Paratoner sistemi (aktif)", unit: "ad" },
  { code: "33.450", category: "Elektrik", name: "Kapı zili + diafon ünitesi", unit: "ad" },
  { code: "33.460", category: "Elektrik", name: "Görüntülü diafon sistemi", unit: "ad" },
  { code: "33.470", category: "Elektrik", name: "Yangın algılama dedektörü (duman)", unit: "ad" },
  { code: "33.480", category: "Elektrik", name: "Yangın alarm butonu", unit: "ad" },

  // ====== MEKANİK TESİSAT ======
  { code: "40.100", category: "Mekanik Tesisat", name: "Doğalgaz kombi montajı (24 kW)", unit: "ad", description: "Yoğuşmalı veya konvansiyonel kombi montajı.\nBaca, gaz girişi, su girişi/çıkışı bağlantıları dahil." },
  { code: "40.110", category: "Mekanik Tesisat", name: "Yerden ısıtma serpantin (PEX)", unit: "m²" },
  { code: "40.120", category: "Mekanik Tesisat", name: "Panel radyatör (600 mm)", unit: "ad" },
  { code: "40.130", category: "Mekanik Tesisat", name: "Havlupan (banyo radyatörü)", unit: "ad" },
  { code: "40.140", category: "Mekanik Tesisat", name: "Split klima iç + dış ünite (12000 BTU)", unit: "ad" },
  { code: "40.150", category: "Mekanik Tesisat", name: "VRV/VRF iç ünite", unit: "ad" },
  { code: "40.160", category: "Mekanik Tesisat", name: "Havalandırma fanı (banyo/wc)", unit: "ad" },
  { code: "40.170", category: "Mekanik Tesisat", name: "Mekanik havalandırma kanalı (galvaniz)", unit: "m²" },
  { code: "40.180", category: "Mekanik Tesisat", name: "Yangın söndürme sprinkler ucu", unit: "ad" },
  { code: "40.190", category: "Mekanik Tesisat", name: "Yangın hidrant kabini (dolaplı)", unit: "ad" },

  // ====== ASANSÖR ======
  { code: "50.100", category: "Asansör", name: "Halatlı asansör (4 kişi, 320 kg)", unit: "ad", description: "Makine daireli/dairesiz halatlı asansör.\n4 durak, 320 kg taşıma kapasitesi.\nKabin, kapı, tablo ve montaj komple." },
  { code: "50.110", category: "Asansör", name: "Halatlı asansör (8 kişi, 630 kg)", unit: "ad" },
  { code: "50.120", category: "Asansör", name: "Hidrolik asansör", unit: "ad" },
  { code: "50.130", category: "Asansör", name: "Engelli/yük asansörü", unit: "ad" },

  // ====== CEPHE ======
  { code: "10.300.4451", category: "Cephe", name: "Mantolama (5 cm EPS + sıva + boya)", unit: "m²", description: "Yapıştırıcı + dübel + EPS levha + file donatılı sıva + dekoratif kaplama + dış cephe boyası.\nTüm katmanlar ve işçilik dahildir." },
  { code: "10.300.4452", category: "Cephe", name: "Mantolama (5 cm taşyünü) + dış cephe boya", unit: "m²" },
  { code: "10.300.4460", category: "Cephe", name: "Mantolama dekoratif kaplama (mineral sıva)", unit: "m²" },
  { code: "10.300.4470", category: "Cephe", name: "Doğal taş cephe kaplama (granit/traverten)", unit: "m²" },
  { code: "10.300.4480", category: "Cephe", name: "Kompozit panel (alüminyum) cephe", unit: "m²" },
  { code: "10.300.4490", category: "Cephe", name: "Giydirme cam cephe (curtain wall)", unit: "m²" },
  { code: "10.300.4500", category: "Cephe", name: "Brüt beton cephe (pürüzsüz)", unit: "m²" },

  // ====== ÇEVRE DÜZENLEME ======
  { code: "18.461", category: "Çevre Düzenleme", name: "Bordür taşı yerleştirilmesi", unit: "m", description: "Beton/granit bordür taşı.\nBeton ile sabitleme ve derz dolgusu dahildir." },
  { code: "18.465", category: "Çevre Düzenleme", name: "Beton kilitli parke taşı döşenmesi", unit: "m²", description: "6-8 cm kalınlıkta beton kilitli parke.\nKum yatak hazırlığı, döşeme, derz kumu ve sıkıştırma dahildir." },
  { code: "18.470", category: "Çevre Düzenleme", name: "Yağmursuyu ızgarası", unit: "ad" },
  { code: "18.480", category: "Çevre Düzenleme", name: "Yeşil alan tesviyesi + bitkisel toprak", unit: "m²" },
  { code: "18.485", category: "Çevre Düzenleme", name: "Çim ekimi + sulama hattı", unit: "m²" },
  { code: "18.490", category: "Çevre Düzenleme", name: "Damla sulama sistemi", unit: "m" },
  { code: "18.495", category: "Çevre Düzenleme", name: "Bahçe aydınlatma direği (LED)", unit: "ad" },
  { code: "18.500", category: "Çevre Düzenleme", name: "Çitle çevirme (tel örgü) (h=1.5 m)", unit: "m" },
  { code: "18.510", category: "Çevre Düzenleme", name: "Beton bahçe duvarı + kaplama", unit: "m²" },
  { code: "18.520", category: "Çevre Düzenleme", name: "Pergola/güneşlik (ahşap/metal)", unit: "m²" },

  // ====== YIKIM VE SÖKÜM ======
  { code: "70.100", category: "Yıkım ve Söküm", name: "Tuğla duvar yıkımı + nakli", unit: "m³", description: "Mevcut duvarın el veya hidrolik kırıcı ile yıkılması.\nMolozun toplanıp döküm sahasına nakli dahildir." },
  { code: "70.110", category: "Yıkım ve Söküm", name: "Betonarme yapı yıkımı (kontrollü)", unit: "m³" },
  { code: "70.120", category: "Yıkım ve Söküm", name: "Sıva sökümü", unit: "m²" },
  { code: "70.130", category: "Yıkım ve Söküm", name: "Seramik/karo sökümü", unit: "m²" },
  { code: "70.140", category: "Yıkım ve Söküm", name: "Şap sökümü", unit: "m²" },
  { code: "70.150", category: "Yıkım ve Söküm", name: "Kapı/pencere sökümü", unit: "ad" },
  { code: "70.160", category: "Yıkım ve Söküm", name: "Çatı kaplama sökümü", unit: "m²" },
  { code: "70.170", category: "Yıkım ve Söküm", name: "Sıhhi tesisat sökümü", unit: "ad" },
  { code: "70.180", category: "Yıkım ve Söküm", name: "Elektrik tesisat sökümü", unit: "m²" },
];
