export interface ConstructionMaterial {
  category: string;
  name: string;
  defaultUnit?: string;
}

export const MATERIAL_CATEGORIES = [
  "Beton ve Çimento",
  "Demir ve Çelik",
  "Agrega ve Dolgu",
  "Duvar ve Kagir",
  "Kalıp ve İskele",
  "Su Yalıtımı",
  "Isı Yalıtımı",
  "Alçı Panel ve Profil",
  "Sıva ve Şap",
  "Yapıştırıcı ve Derz",
  "Seramik ve Porselen",
  "Taş ve Mermer",
  "Zemin Kaplamaları",
  "Boya ve Vernik",
  "Doğrama ve Cam",
  "Çatı ve Saçak",
  "Sıhhi Tesisat",
  "Elektrik",
  "Hırdavat ve Bağlantı",
  "Diğer",
] as const;

export type MaterialCategory = (typeof MATERIAL_CATEGORIES)[number];

export const CONSTRUCTION_MATERIALS: ConstructionMaterial[] = [
  // ====== BETON VE ÇİMENTO ======
  { category: "Beton ve Çimento", name: "Hazır Beton C16/20", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C20/25", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C25/30", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C30/37", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C35/45", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C40/50", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Grobeton (Tesviye Betonu)", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hızlı Priz Çimento", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Çimento CEM I 42.5 R", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Çimento CEM II 32.5 R", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Çimento CEM II 42.5 R", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Beyaz Çimento", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Sönmüş Kireç", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Beton Akışkanlaştırıcı Katkı", defaultUnit: "LT" },
  { category: "Beton ve Çimento", name: "Beton Antifrizi", defaultUnit: "LT" },
  { category: "Beton ve Çimento", name: "Kürleme Malzemesi (Akrilik Sıvı)", defaultUnit: "LT" },
  { category: "Beton ve Çimento", name: "Çimento Şerbeti", defaultUnit: "KG" },

  // ====== DEMİR VE ÇELİK ======
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø8", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø10", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø12", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø14", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø16", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø18", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø20", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø22", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø25", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Düz Demir Ø6 (Filiz)", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q188", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q221", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q257", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q335", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Köşebent Demir", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "NPI / NPU Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "IPE Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "HEA / HEB Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Lama Demir", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Kutu Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Düz Siyah Sac", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Galvanizli Sac", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Galvanize Sac Plaka", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Profil Demiri", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Bağlama Teli", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Kaynak Kordonu", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Alüminyum Plaka", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Bakırdan Levha", defaultUnit: "M2" },

  // ====== AGREGA VE DOLGU ======
  { category: "Agrega ve Dolgu", name: "Mıcır 0/5", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Mıcır 5/15", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Mıcır 15/25", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Yıkanmış Kum", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Çakıl", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Kum-Çakıl Karışım", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Kırmataş", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Stabilize", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Tüvenan", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Silis (Kuvars) Kumu ve Çakılı", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Filler (Taş Tozu)", defaultUnit: "TON" },
  { category: "Agrega ve Dolgu", name: "Bentonit", defaultUnit: "TON" },

  // ====== DUVAR VE KAGİR ======
  { category: "Duvar ve Kagir", name: "Tuğla 19 (Yatay Delikli)", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Tuğla 13.5", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Tuğla 8.5", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Bims Blok 8.5 cm", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Bims Blok 13.5 cm", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Bims Blok 19 cm", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Gazbeton 7.5 cm", defaultUnit: "M3" },
  { category: "Duvar ve Kagir", name: "Gazbeton 10 cm", defaultUnit: "M3" },
  { category: "Duvar ve Kagir", name: "Gazbeton 12.5 cm", defaultUnit: "M3" },
  { category: "Duvar ve Kagir", name: "Gazbeton 15 cm", defaultUnit: "M3" },
  { category: "Duvar ve Kagir", name: "Gazbeton 20 cm", defaultUnit: "M3" },
  { category: "Duvar ve Kagir", name: "Gazbeton Tutkalı", defaultUnit: "TORBA" },
  { category: "Duvar ve Kagir", name: "Beton Briket 20 cm", defaultUnit: "ADET" },
  { category: "Duvar ve Kagir", name: "Andezit Taş", defaultUnit: "M2" },
  { category: "Duvar ve Kagir", name: "Lentil (Hatıl)", defaultUnit: "ADET" },

  // ====== KALIP VE İSKELE ======
  { category: "Kalıp ve İskele", name: "Plywood Kalıp Levhası 18 mm", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Plywood Kalıp Levhası 21 mm", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "OSB Levha", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Çam Kerestesi I. Sınıf", defaultUnit: "M3" },
  { category: "Kalıp ve İskele", name: "Çam Kerestesi II. Sınıf", defaultUnit: "M3" },
  { category: "Kalıp ve İskele", name: "Kalıp Direği 3 m", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Kalıp Direği 4 m", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Çelik Kalıp Direği (Telgon)", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Mertek", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Lata / Çıta", defaultUnit: "ADET" },
  { category: "Kalıp ve İskele", name: "Kalıp Yağı", defaultUnit: "LT" },
  { category: "Kalıp ve İskele", name: "Çelik Kalıp Panel", defaultUnit: "M2" },
  { category: "Kalıp ve İskele", name: "Tünel Kalıp", defaultUnit: "M2" },

  // ====== SU YALITIMI ======
  { category: "Su Yalıtımı", name: "Bitümlü Membran 3 mm (APP)", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Bitümlü Membran 4 mm (SBS)", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Bitüm Emülsiyonu (TS 113)", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "Likit Membran", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "Bitüm Astar (Soğuk)", defaultUnit: "LT" },
  { category: "Su Yalıtımı", name: "Çimento Esaslı Su Yalıtımı", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "Polyurethane Su Yalıtımı", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "EPDM Membran", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "PVC Membran", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Su Buharı Geçişine Açık Su Yalıtım Örtüsü", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "HDPE Drenaj ve Koruma Levhası", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Geotekstil (Filtre Kumaşı)", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Su Tutucu Bant (Şişen)", defaultUnit: "MT" },
  { category: "Su Yalıtımı", name: "Bitümlü Karton", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Plastik Esaslı Sızdırmazlık Bandı", defaultUnit: "MT" },

  // ====== ISI YALITIMI ======
  { category: "Isı Yalıtımı", name: "XPS 300 kPa 3 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS 300 kPa 4 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS 300 kPa 5 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS 300 kPa 6 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS 300 kPa 8 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "EPS Isı Yalıtımı 3 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "EPS Isı Yalıtımı 5 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "EPS Isı Yalıtımı 8 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Karbon EPS (Gri) 5 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Cam Yünü", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Taş Yünü Levha", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Isı Yalıtım Levhaları Yapıştırıcısı", defaultUnit: "TORBA" },
  { category: "Isı Yalıtımı", name: "Isı Yalıtım Levha Sıvası", defaultUnit: "TORBA" },
  { category: "Isı Yalıtımı", name: "Plastik Çivili Isı Yalıtım Dübeli", defaultUnit: "ADET" },
  { category: "Isı Yalıtımı", name: "Mantolama Dübeli", defaultUnit: "ADET" },
  { category: "Isı Yalıtımı", name: "Sıva Filesi (Cam Tülü)", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "PVC Köşe Profili (Fileli)", defaultUnit: "MT" },
  { category: "Isı Yalıtımı", name: "Damla Profili", defaultUnit: "MT" },
  { category: "Isı Yalıtımı", name: "Akrilik Cephe Sıvası", defaultUnit: "KG" },
  { category: "Isı Yalıtımı", name: "Mineral Cephe Sıvası", defaultUnit: "KG" },
  { category: "Isı Yalıtımı", name: "Cephe Astarı", defaultUnit: "LT" },
  { category: "Isı Yalıtımı", name: "Poliüretan Sprey Köpük", defaultUnit: "KG" },

  // ====== ALÇI PANEL VE PROFİL ======
  { category: "Alçı Panel ve Profil", name: "Alçı Levha 12.5 mm (FH2)", defaultUnit: "M2" },
  { category: "Alçı Panel ve Profil", name: "Alçı Levha 15 mm (FH2)", defaultUnit: "M2" },
  { category: "Alçı Panel ve Profil", name: "Alçı Levha Yeşil (Su İtici)", defaultUnit: "M2" },
  { category: "Alçı Panel ve Profil", name: "Alçı Levha Pembe (Yangın)", defaultUnit: "M2" },
  { category: "Alçı Panel ve Profil", name: "Duvar U Profil 50 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Duvar C Profil 50 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Duvar U Profil 75 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Duvar C Profil 75 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Duvar U Profil 100 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Duvar C Profil 100 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Tavan U Profil 28 (0.50 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Tavan C Profil 60 (0.60 mm)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "T24 Ana Taşıyıcı", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "T24 Ara Taşıyıcı", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Kenar L Profili", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Kenar Z Profili", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Gizli Taşıyıcılı Profil (Clip-In)", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Gizli Taşıyıcılı Alüminyum Kenar C Profili", defaultUnit: "MT" },
  { category: "Alçı Panel ve Profil", name: "Askı Çubuğu", defaultUnit: "ADET" },
  { category: "Alçı Panel ve Profil", name: "Çiftli Yay", defaultUnit: "ADET" },
  { category: "Alçı Panel ve Profil", name: "Birleşim Klipsi", defaultUnit: "ADET" },
  { category: "Alçı Panel ve Profil", name: "Taşıyıcı Ek Parçası", defaultUnit: "ADET" },
  { category: "Alçı Panel ve Profil", name: "Bastırma Klipsi", defaultUnit: "ADET" },
  { category: "Alçı Panel ve Profil", name: "Alçı Levha Vidası (Borazan)", defaultUnit: "KUTU" },
  { category: "Alçı Panel ve Profil", name: "Derz Bandı", defaultUnit: "RULO" },
  { category: "Alçı Panel ve Profil", name: "Asma Tavan Plakası 60x60", defaultUnit: "ADET" },

  // ====== SIVA VE ŞAP ======
  { category: "Sıva ve Şap", name: "Hazır Sıva Harcı (Makine)", defaultUnit: "TORBA" },
  { category: "Sıva ve Şap", name: "Çimento Esaslı Sıva", defaultUnit: "TORBA" },
  { category: "Sıva ve Şap", name: "Alçı Sıva", defaultUnit: "TORBA" },
  { category: "Sıva ve Şap", name: "Saten Alçı", defaultUnit: "TORBA" },
  { category: "Sıva ve Şap", name: "Sıva Astarı", defaultUnit: "KG" },
  { category: "Sıva ve Şap", name: "Tamir Macunu", defaultUnit: "KG" },
  { category: "Sıva ve Şap", name: "Hazır Şap Harcı", defaultUnit: "TORBA" },
  { category: "Sıva ve Şap", name: "Anhidrit Şap", defaultUnit: "M3" },
  { category: "Sıva ve Şap", name: "Şap Filesi", defaultUnit: "M2" },
  { category: "Sıva ve Şap", name: "Şap Profili (Dilatasyon)", defaultUnit: "MT" },
  { category: "Sıva ve Şap", name: "Polietilen Şilte (Altlık)", defaultUnit: "M2" },

  // ====== YAPIŞTIRIC VE DERZ ======
  { category: "Yapıştırıcı ve Derz", name: "Karo Yapıştırıcı C2TE", defaultUnit: "TORBA" },
  { category: "Yapıştırıcı ve Derz", name: "Seramik Yapıştırıcı C1", defaultUnit: "TORBA" },
  { category: "Yapıştırıcı ve Derz", name: "Granit Yapıştırıcı (Beyaz C2)", defaultUnit: "TORBA" },
  { category: "Yapıştırıcı ve Derz", name: "Derz Dolgu Malzemesi CG1", defaultUnit: "KG" },
  { category: "Yapıştırıcı ve Derz", name: "Derz Dolgu Malzemesi CG2AW (Su İtici)", defaultUnit: "KG" },
  { category: "Yapıştırıcı ve Derz", name: "Epoksi Derz", defaultUnit: "KG" },
  { category: "Yapıştırıcı ve Derz", name: "Akrilik Esaslı PVC Yapıştırıcı", defaultUnit: "KG" },
  { category: "Yapıştırıcı ve Derz", name: "Sentetik Tutkal", defaultUnit: "KG" },
  { category: "Yapıştırıcı ve Derz", name: "Silikon (Şeffaf 310 ml)", defaultUnit: "ADET" },
  { category: "Yapıştırıcı ve Derz", name: "Silikon (Beyaz 310 ml)", defaultUnit: "ADET" },
  { category: "Yapıştırıcı ve Derz", name: "Polyurethane Köpük", defaultUnit: "ADET" },
  { category: "Yapıştırıcı ve Derz", name: "Lehim", defaultUnit: "KG" },
  { category: "Yapıştırıcı ve Derz", name: "Arap Sabunu (Kalıp Yağı İkamesi)", defaultUnit: "KG" },

  // ====== SERAMİK VE PORSELEN ======
  { category: "Seramik ve Porselen", name: "Seramik Yer 30x60", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Seramik Yer 45x45", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Seramik Yer 60x60", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Seramik Duvar 30x60", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Porselen Yer 60x60", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Porselen Yer 80x80", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Porselen Yer 60x120", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Yer Karosu (Standart)", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Mozaik Karo", defaultUnit: "M2" },
  { category: "Seramik ve Porselen", name: "Süpürgelik Seramik", defaultUnit: "MT" },
  { category: "Seramik ve Porselen", name: "Bordür", defaultUnit: "MT" },

  // ====== TAŞ VE MERMER ======
  { category: "Taş ve Mermer", name: "Mermer Döşeme (Fiyonlu)", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Granit Döşeme", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Andezit Kaplama", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Travertine", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Doğal Taş (Kaba)", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Mermer Agregalı Terrazo Karo", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Granit Agregalı Terrazo Karo", defaultUnit: "M2" },
  { category: "Taş ve Mermer", name: "Mermer Süpürgelik", defaultUnit: "MT" },
  { category: "Taş ve Mermer", name: "Mermer Denizlik / Eşik", defaultUnit: "ADET" },
  { category: "Taş ve Mermer", name: "Taş Küpeşte", defaultUnit: "MT" },

  // ====== ZEMİN KAPLAMALARI ======
  { category: "Zemin Kaplamaları", name: "PVC Esaslı Yer Döşemesi (Homojen)", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "PVC Yer Kaplaması (Heterojen)", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Laminat Parke 8 mm", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Laminat Parke 12 mm", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Masif Parke", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Lamine Parke", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Ahşap Döşeme Tahtası", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Halı", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Endüstriyel Halı", defaultUnit: "M2" },
  { category: "Zemin Kaplamaları", name: "Zemin Kaplaması Yapıştırıcısı", defaultUnit: "KG" },
  { category: "Zemin Kaplamaları", name: "Ahşap Süpürgelik", defaultUnit: "MT" },

  // ====== BOYA VE VERNİK ======
  { category: "Boya ve Vernik", name: "İç Cephe Plastik Boya", defaultUnit: "KG" },
  { category: "Boya ve Vernik", name: "Dış Cephe Boyası (Silikon)", defaultUnit: "KG" },
  { category: "Boya ve Vernik", name: "Akrilik Boya", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Yağlı Boya", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Antipas Astar (Kırmızı)", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Boya Astarı", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Vernik (Su Bazlı)", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Vernik (Sentetik)", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Boya Macunu", defaultUnit: "KG" },
  { category: "Boya ve Vernik", name: "Tiner / Çözücü", defaultUnit: "LT" },
  { category: "Boya ve Vernik", name: "Epoksi Zemin Boyası", defaultUnit: "KG" },
  { category: "Boya ve Vernik", name: "Renklendirici (Pigment)", defaultUnit: "KG" },
  { category: "Boya ve Vernik", name: "Zımpara Kağıdı", defaultUnit: "ADET" },

  // ====== DOĞRAMA VE CAM ======
  { category: "Doğrama ve Cam", name: "PVC Pencere", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Alüminyum Pencere", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Ahşap Pencere", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "PVC Kapı", defaultUnit: "ADET" },
  { category: "Doğrama ve Cam", name: "İç Kapı (Ahşap Kaplama)", defaultUnit: "ADET" },
  { category: "Doğrama ve Cam", name: "Çelik Kapı", defaultUnit: "ADET" },
  { category: "Doğrama ve Cam", name: "Alüminyum Dış Kapı", defaultUnit: "ADET" },
  { category: "Doğrama ve Cam", name: "Garaj Kapısı", defaultUnit: "ADET" },
  { category: "Doğrama ve Cam", name: "Cam 4 mm (Düz)", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Çift Cam 4+12+4", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Üçlü Cam (Low-E)", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Pencere Aksesuar Takımı", defaultUnit: "TAKIM" },
  { category: "Doğrama ve Cam", name: "Kapı Aksesuar Takımı", defaultUnit: "TAKIM" },
  { category: "Doğrama ve Cam", name: "Sineklik (Folding)", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Ahşap Lambri", defaultUnit: "M2" },
  { category: "Doğrama ve Cam", name: "Ahşap Küpeşte", defaultUnit: "MT" },

  // ====== ÇATI VE SAÇAK ======
  { category: "Çatı ve Saçak", name: "Marsilya Kiremit", defaultUnit: "ADET" },
  { category: "Çatı ve Saçak", name: "Betopan / Granül Kaplı Levha", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Bitümlü Şingıl", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Sandviç Panel 4 cm", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Sandviç Panel 6 cm", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Sandviç Panel 10 cm", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Trapez Sac (Galvaniz)", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Çinko Levha", defaultUnit: "M2" },
  { category: "Çatı ve Saçak", name: "Oluk Çinko (Su Oluğu)", defaultUnit: "MT" },
  { category: "Çatı ve Saçak", name: "Yağmur İniş Borusu", defaultUnit: "MT" },
  { category: "Çatı ve Saçak", name: "Saçak Tahtası / Kaplaması", defaultUnit: "MT" },
  { category: "Çatı ve Saçak", name: "Mahya", defaultUnit: "MT" },
  { category: "Çatı ve Saçak", name: "Mahya Tespit Aparatı", defaultUnit: "ADET" },
  { category: "Çatı ve Saçak", name: "EPDM Contalı Panel Montaj Vidası", defaultUnit: "ADET" },

  // ====== SIHHİ TESİSAT ======
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø20", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø25", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø32", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø40", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø50", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø75", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø100", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø160", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "Polietilen Su Borusu PE100", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PEX Boru", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "Bakır Boru", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Fittings (Dirsek / Te / Manşon)", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Klozet Takımı (Rezervuarlı)", defaultUnit: "TAKIM" },
  { category: "Sıhhi Tesisat", name: "Asma Klozet (Gömme Rezervuar)", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Lavabo", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Lavabo Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Banyo / Duş Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Mutfak Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Eviye (Paslanmaz)", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Küvet", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Duş Teknesi", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Yer Süzgeci", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Vana (Küresel)", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Boyler / Termosifon", defaultUnit: "ADET" },

  // ====== ELEKTRİK ======
  { category: "Elektrik", name: "PVC Spiral Boru Ø13", defaultUnit: "MT" },
  { category: "Elektrik", name: "PVC Spiral Boru Ø16", defaultUnit: "MT" },
  { category: "Elektrik", name: "PVC Spiral Boru Ø23", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x1.5 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x2.5 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x4 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYY 4x6 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYY 4x10 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NHXMH (Halojensiz) Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "Anahtar (Tek / Komütatör)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Priz (Topraklı)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 10A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 16A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 25A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Kaçak Akım Rölesi (30 mA)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Pano (Sigorta Kutusu)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "LED Aydınlatma Armatürü", defaultUnit: "ADET" },
  { category: "Elektrik", name: "LED Spot", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Topraklama Çubuğu", defaultUnit: "ADET" },

  // ====== HIRDAVAT VE BAĞLANTI ======
  { category: "Hırdavat ve Bağlantı", name: "Galvanizli Çivi 3\"", defaultUnit: "KG" },
  { category: "Hırdavat ve Bağlantı", name: "Galvanizli Çivi 4\"", defaultUnit: "KG" },
  { category: "Hırdavat ve Bağlantı", name: "Çivi 6\"", defaultUnit: "KG" },
  { category: "Hırdavat ve Bağlantı", name: "Vida ve Plastik Dübel (Set)", defaultUnit: "KUTU" },
  { category: "Hırdavat ve Bağlantı", name: "Sunta Vidası (Torx)", defaultUnit: "KUTU" },
  { category: "Hırdavat ve Bağlantı", name: "Dübel 6 mm", defaultUnit: "KUTU" },
  { category: "Hırdavat ve Bağlantı", name: "Dübel 8 mm", defaultUnit: "KUTU" },
  { category: "Hırdavat ve Bağlantı", name: "Dübel 10 mm", defaultUnit: "KUTU" },
  { category: "Hırdavat ve Bağlantı", name: "Çelik Dübel (Fischer Tip)", defaultUnit: "ADET" },
  { category: "Hırdavat ve Bağlantı", name: "Borazan Vida (Alçıpan)", defaultUnit: "KUTU" },
  { category: "Hırdavat ve Bağlantı", name: "Klips 7.5 cm", defaultUnit: "ADET" },
  { category: "Hırdavat ve Bağlantı", name: "Ekleme Parçası (Profil)", defaultUnit: "ADET" },
  { category: "Hırdavat ve Bağlantı", name: "Maskeleme Bandı", defaultUnit: "RULO" },
  { category: "Hırdavat ve Bağlantı", name: "İzolasyon Bandı", defaultUnit: "RULO" },
  { category: "Hırdavat ve Bağlantı", name: "Matkap Ucu (Beton)", defaultUnit: "ADET" },

  // ====== DİĞER ======
  { category: "Diğer", name: "Mazot", defaultUnit: "LT" },
  { category: "Diğer", name: "Benzin", defaultUnit: "LT" },
  { category: "Diğer", name: "Likit Petrol Gazı (LPG)", defaultUnit: "KG" },
  { category: "Diğer", name: "Su (Şebeke)", defaultUnit: "M3" },
  { category: "Diğer", name: "Jel Dinamit", defaultUnit: "KG" },
  { category: "Diğer", name: "Kapsül", defaultUnit: "ADET" },
  { category: "Diğer", name: "Fitil", defaultUnit: "MT" },
  { category: "Diğer", name: "ANFO Karışımı", defaultUnit: "KG" },
];

export function findMaterialByName(name: string): ConstructionMaterial | undefined {
  if (!name) return undefined;
  const norm = name.trim().toLowerCase();
  return CONSTRUCTION_MATERIALS.find((m) => m.name.toLowerCase() === norm);
}

export function getMaterialsByCategory(category: MaterialCategory): ConstructionMaterial[] {
  return CONSTRUCTION_MATERIALS.filter((m) => m.category === category);
}
