export interface ConstructionMaterial {
  category: string;
  name: string;
  defaultUnit?: string;
}

export const MATERIAL_CATEGORIES = [
  "Beton ve Çimento",
  "Demir ve Çelik",
  "Agrega",
  "Duvar",
  "Kalıp ve Kereste",
  "Su Yalıtımı",
  "Isı Yalıtımı",
  "Sıva ve Alçı",
  "Boya",
  "Seramik ve Mermer",
  "Sıhhi Tesisat",
  "Elektrik",
  "Doğrama",
  "Çatı",
  "Asma Tavan",
  "Şap",
  "Cephe (Mantolama)",
  "Hırdavat",
  "Diğer",
] as const;

export type MaterialCategory = (typeof MATERIAL_CATEGORIES)[number];

export const CONSTRUCTION_MATERIALS: ConstructionMaterial[] = [
  // ====== KABA İNŞAAT ======

  // Beton ve Çimento
  { category: "Beton ve Çimento", name: "Hazır Beton C16/20", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C20/25", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C25/30", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C30/37", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C35/45", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hazır Beton C40/50", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Şap Betonu", defaultUnit: "M3" },
  { category: "Beton ve Çimento", name: "Hızlı Priz Çimento", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Çimento CEM I 42.5 R", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Çimento CEM II 32.5 R", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Çimento CEM II 42.5 R", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Beyaz Çimento", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Sönmüş Kireç", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Yapı Kireci", defaultUnit: "TORBA" },
  { category: "Beton ve Çimento", name: "Beton Akışkanlaştırıcı (Katkı)", defaultUnit: "LT" },
  { category: "Beton ve Çimento", name: "Beton Antifrizi", defaultUnit: "LT" },

  // Demir ve Çelik
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø8", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø10", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø12", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø14", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø16", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø18", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø20", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø22", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø25", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø28", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Nervürlü İnşaat Demiri Ø32", defaultUnit: "TON" },
  { category: "Demir ve Çelik", name: "Düz Demir Ø6 (Filiz)", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Düz Demir Ø8 (Filiz)", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q188", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q221", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q257", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q295", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q335", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Hasır Çelik Q378", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Köşebent Demir", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "NPI Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "NPU Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "IPE Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "HEA / HEB Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Lama Demir", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Kutu Profil", defaultUnit: "KG" },
  { category: "Demir ve Çelik", name: "Saç Levha", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Galvaniz Saç", defaultUnit: "M2" },
  { category: "Demir ve Çelik", name: "Bağlama Teli", defaultUnit: "KG" },

  // Agrega
  { category: "Agrega", name: "Mıcır 0/5", defaultUnit: "TON" },
  { category: "Agrega", name: "Mıcır 5/15", defaultUnit: "TON" },
  { category: "Agrega", name: "Mıcır 15/25", defaultUnit: "TON" },
  { category: "Agrega", name: "Yıkanmış Kum", defaultUnit: "TON" },
  { category: "Agrega", name: "Çakıl", defaultUnit: "TON" },
  { category: "Agrega", name: "Kum-Çakıl Karışım", defaultUnit: "TON" },
  { category: "Agrega", name: "Kırmataş", defaultUnit: "TON" },
  { category: "Agrega", name: "Stabilize", defaultUnit: "TON" },
  { category: "Agrega", name: "Tüvenan", defaultUnit: "TON" },
  { category: "Agrega", name: "Filler (Taş Tozu)", defaultUnit: "TON" },

  // Duvar
  { category: "Duvar", name: "Tuğla 19 (Yatay Delikli)", defaultUnit: "ADET" },
  { category: "Duvar", name: "Tuğla 13.5", defaultUnit: "ADET" },
  { category: "Duvar", name: "Tuğla 8.5", defaultUnit: "ADET" },
  { category: "Duvar", name: "Tuğla 5", defaultUnit: "ADET" },
  { category: "Duvar", name: "Bims Blok 8.5 cm", defaultUnit: "ADET" },
  { category: "Duvar", name: "Bims Blok 13.5 cm", defaultUnit: "ADET" },
  { category: "Duvar", name: "Bims Blok 19 cm", defaultUnit: "ADET" },
  { category: "Duvar", name: "Bims Blok 20 cm", defaultUnit: "ADET" },
  { category: "Duvar", name: "Gazbeton 7.5 cm", defaultUnit: "M3" },
  { category: "Duvar", name: "Gazbeton 10 cm", defaultUnit: "M3" },
  { category: "Duvar", name: "Gazbeton 12.5 cm", defaultUnit: "M3" },
  { category: "Duvar", name: "Gazbeton 15 cm", defaultUnit: "M3" },
  { category: "Duvar", name: "Gazbeton 20 cm", defaultUnit: "M3" },
  { category: "Duvar", name: "Gazbeton 25 cm", defaultUnit: "M3" },
  { category: "Duvar", name: "Gazbeton Yapıştırıcı", defaultUnit: "TORBA" },
  { category: "Duvar", name: "Briket", defaultUnit: "ADET" },
  { category: "Duvar", name: "Beton Briket 20 cm", defaultUnit: "ADET" },
  { category: "Duvar", name: "Andezit Taş", defaultUnit: "M2" },
  { category: "Duvar", name: "Refrakter Tuğla", defaultUnit: "ADET" },
  { category: "Duvar", name: "Lentil (Hatıl)", defaultUnit: "ADET" },

  // Kalıp ve Kereste
  { category: "Kalıp ve Kereste", name: "Plywood Kalıp Levhası 18 mm", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Plywood Kalıp Levhası 21 mm", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "OSB Levha", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Kalıp Direği 3 m", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Kalıp Direği 4 m", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Çelik Kalıp Direği (Telgon)", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Mertek", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Kereste 5x10", defaultUnit: "MT" },
  { category: "Kalıp ve Kereste", name: "Kereste 10x10", defaultUnit: "MT" },
  { category: "Kalıp ve Kereste", name: "Lata / Çıta", defaultUnit: "ADET" },
  { category: "Kalıp ve Kereste", name: "Kalıp Yağı", defaultUnit: "LT" },
  { category: "Kalıp ve Kereste", name: "Çelik Kalıp Panel", defaultUnit: "M2" },
  { category: "Kalıp ve Kereste", name: "Tünel Kalıp", defaultUnit: "M2" },

  // Su Yalıtımı
  { category: "Su Yalıtımı", name: "Bitümlü Membran 3 mm", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Bitümlü Membran 4 mm", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Likit Membran", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "Bitüm Astar", defaultUnit: "LT" },
  { category: "Su Yalıtımı", name: "Çimento Esaslı Su Yalıtımı", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "Polyurethane Su Yalıtımı", defaultUnit: "KG" },
  { category: "Su Yalıtımı", name: "EPDM Membran", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "PVC Membran", defaultUnit: "M2" },
  { category: "Su Yalıtımı", name: "Su Tutucu Bant", defaultUnit: "MT" },
  { category: "Su Yalıtımı", name: "Drenaj Levhası", defaultUnit: "M2" },

  // Isı Yalıtımı
  { category: "Isı Yalıtımı", name: "XPS Isı Yalıtımı 3 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS Isı Yalıtımı 4 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS Isı Yalıtımı 5 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS Isı Yalıtımı 6 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "XPS Isı Yalıtımı 8 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "EPS Isı Yalıtımı 3 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "EPS Isı Yalıtımı 5 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "EPS Isı Yalıtımı 8 cm", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Cam Yünü", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Taş Yünü", defaultUnit: "M2" },
  { category: "Isı Yalıtımı", name: "Poliüretan Sprey Köpük", defaultUnit: "KG" },

  // ====== İNCE İNŞAAT ======

  // Sıva ve Alçı
  { category: "Sıva ve Alçı", name: "Hazır Sıva Harcı", defaultUnit: "TORBA" },
  { category: "Sıva ve Alçı", name: "Çimento Esaslı Sıva", defaultUnit: "TORBA" },
  { category: "Sıva ve Alçı", name: "Makine Sıvası", defaultUnit: "TORBA" },
  { category: "Sıva ve Alçı", name: "Saten Alçı", defaultUnit: "TORBA" },
  { category: "Sıva ve Alçı", name: "Kartonpiyer Alçısı", defaultUnit: "TORBA" },
  { category: "Sıva ve Alçı", name: "Alçı Sıva", defaultUnit: "TORBA" },
  { category: "Sıva ve Alçı", name: "Sıva Astarı", defaultUnit: "KG" },
  { category: "Sıva ve Alçı", name: "Tamir Macunu", defaultUnit: "KG" },

  // Boya
  { category: "Boya", name: "İç Cephe Plastik Boya", defaultUnit: "KG" },
  { category: "Boya", name: "Dış Cephe Boyası", defaultUnit: "KG" },
  { category: "Boya", name: "Silikonlu Dış Cephe Boyası", defaultUnit: "KG" },
  { category: "Boya", name: "Akrilik Boya", defaultUnit: "LT" },
  { category: "Boya", name: "Yağlı Boya", defaultUnit: "LT" },
  { category: "Boya", name: "Boya Astarı", defaultUnit: "LT" },
  { category: "Boya", name: "Vernik (Su Bazlı)", defaultUnit: "LT" },
  { category: "Boya", name: "Vernik (Sentetik)", defaultUnit: "LT" },
  { category: "Boya", name: "Boya Macunu", defaultUnit: "KG" },
  { category: "Boya", name: "Tiner / Çözücü", defaultUnit: "LT" },
  { category: "Boya", name: "Antibakteriyel Boya", defaultUnit: "LT" },
  { category: "Boya", name: "Renklendirici (Pigment)", defaultUnit: "KG" },

  // Seramik ve Mermer
  { category: "Seramik ve Mermer", name: "Seramik 30x60", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Seramik 33x33", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Seramik 45x45", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Seramik 60x60", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Seramik 80x80", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Yer Karosu", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Duvar Karosu", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Granit", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Mermer", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Travertine", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Doğal Taş", defaultUnit: "M2" },
  { category: "Seramik ve Mermer", name: "Seramik Yapıştırıcı", defaultUnit: "TORBA" },
  { category: "Seramik ve Mermer", name: "Granit Yapıştırıcı", defaultUnit: "TORBA" },
  { category: "Seramik ve Mermer", name: "Derz Dolgu", defaultUnit: "KG" },
  { category: "Seramik ve Mermer", name: "Süpürgelik", defaultUnit: "MT" },

  // Sıhhi Tesisat
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø20", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø25", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø32", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Boru Ø40", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø50", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø75", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø100", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø125", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PVC Atık Boru Ø160", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "Polietilen Su Borusu", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PEX Boru", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "Bakır Boru", defaultUnit: "MT" },
  { category: "Sıhhi Tesisat", name: "PPRC Fittings (Dirsek/Te)", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Klozet Takımı", defaultUnit: "TAKIM" },
  { category: "Sıhhi Tesisat", name: "Asma Klozet", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Lavabo", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Lavabo Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Banyo Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Mutfak Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Duş Bataryası", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Eviye", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Duş Teknesi", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Küvet", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Sifon", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Yer Süzgeci", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Vana (Küresel)", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Çek Valf", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Boyler", defaultUnit: "ADET" },
  { category: "Sıhhi Tesisat", name: "Termosifon", defaultUnit: "ADET" },

  // Elektrik
  { category: "Elektrik", name: "PVC Spiral Boru Ø13", defaultUnit: "MT" },
  { category: "Elektrik", name: "PVC Spiral Boru Ø16", defaultUnit: "MT" },
  { category: "Elektrik", name: "PVC Spiral Boru Ø23", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x1.5 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x2.5 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x4 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYM 3x6 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYY 4x6 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYY 4x10 Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NHXMH Kablo", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYAF 1x1.5", defaultUnit: "MT" },
  { category: "Elektrik", name: "NYAF 1x2.5", defaultUnit: "MT" },
  { category: "Elektrik", name: "Anahtar (Tek)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Anahtar (Komütatör)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Anahtar (Vavien)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Priz (Topraklı)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Priz (TV/Internet)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 6A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 16A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 25A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Sigorta Otomatı 32A", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Kaçak Akım Rölesi", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Pano (Sigorta Kutusu)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Buat (Kasa)", defaultUnit: "ADET" },
  { category: "Elektrik", name: "LED Aydınlatma Armatürü", defaultUnit: "ADET" },
  { category: "Elektrik", name: "LED Spot", defaultUnit: "ADET" },
  { category: "Elektrik", name: "LED Ampul", defaultUnit: "ADET" },
  { category: "Elektrik", name: "Topraklama Çubuğu", defaultUnit: "ADET" },

  // Doğrama
  { category: "Doğrama", name: "PVC Pencere", defaultUnit: "M2" },
  { category: "Doğrama", name: "Alüminyum Pencere", defaultUnit: "M2" },
  { category: "Doğrama", name: "Ahşap Pencere", defaultUnit: "M2" },
  { category: "Doğrama", name: "Cam 4 mm", defaultUnit: "M2" },
  { category: "Doğrama", name: "Çift Cam 4+12+4", defaultUnit: "M2" },
  { category: "Doğrama", name: "Üçlü Cam (Low-E)", defaultUnit: "M2" },
  { category: "Doğrama", name: "İç Kapı (Ahşap)", defaultUnit: "ADET" },
  { category: "Doğrama", name: "Çelik Kapı", defaultUnit: "ADET" },
  { category: "Doğrama", name: "Alüminyum Dış Kapı", defaultUnit: "ADET" },
  { category: "Doğrama", name: "Garaj Kapısı", defaultUnit: "ADET" },
  { category: "Doğrama", name: "Pencere Aksesuarı", defaultUnit: "TAKIM" },
  { category: "Doğrama", name: "Silikon (Cam)", defaultUnit: "ADET" },

  // Çatı
  { category: "Çatı", name: "Marsilya Kiremit", defaultUnit: "ADET" },
  { category: "Çatı", name: "Granül Kaplı Levha (Bardoline)", defaultUnit: "M2" },
  { category: "Çatı", name: "Sandviç Panel 4 cm", defaultUnit: "M2" },
  { category: "Çatı", name: "Sandviç Panel 6 cm", defaultUnit: "M2" },
  { category: "Çatı", name: "Sandviç Panel 10 cm", defaultUnit: "M2" },
  { category: "Çatı", name: "Çatı OSB", defaultUnit: "M2" },
  { category: "Çatı", name: "Çinko Levha", defaultUnit: "M2" },
  { category: "Çatı", name: "Saçak Tahtası", defaultUnit: "MT" },
  { category: "Çatı", name: "Su Oluğu", defaultUnit: "MT" },
  { category: "Çatı", name: "Yağmur İniş Borusu", defaultUnit: "MT" },
  { category: "Çatı", name: "Bitümlü Şingıl", defaultUnit: "M2" },
  { category: "Çatı", name: "Mahya", defaultUnit: "MT" },

  // Asma Tavan
  { category: "Asma Tavan", name: "Alçıpan 12.5 mm", defaultUnit: "M2" },
  { category: "Asma Tavan", name: "Alçıpan 15 mm", defaultUnit: "M2" },
  { category: "Asma Tavan", name: "Yeşil Alçıpan (Aquapan)", defaultUnit: "M2" },
  { category: "Asma Tavan", name: "Pembe Alçıpan (Yangın)", defaultUnit: "M2" },
  { category: "Asma Tavan", name: "U Profil 27", defaultUnit: "MT" },
  { category: "Asma Tavan", name: "C Profil 60", defaultUnit: "MT" },
  { category: "Asma Tavan", name: "T Profil", defaultUnit: "MT" },
  { category: "Asma Tavan", name: "Asma Tavan Plakası 60x60", defaultUnit: "ADET" },
  { category: "Asma Tavan", name: "Alçıpan Vidası", defaultUnit: "KUTU" },
  { category: "Asma Tavan", name: "Köşe Profili (Galvaniz)", defaultUnit: "MT" },
  { category: "Asma Tavan", name: "Filet (Cam Tülü)", defaultUnit: "MT" },
  { category: "Asma Tavan", name: "Galvaniz Tel Askı", defaultUnit: "ADET" },
  { category: "Asma Tavan", name: "Derz Bandı", defaultUnit: "RULO" },

  // Şap
  { category: "Şap", name: "Hazır Şap Harcı", defaultUnit: "TORBA" },
  { category: "Şap", name: "Anhidrit Şap", defaultUnit: "M3" },
  { category: "Şap", name: "Şap Filesi", defaultUnit: "M2" },
  { category: "Şap", name: "Şap Profili (Dilatasyon)", defaultUnit: "MT" },
  { category: "Şap", name: "Polietilen Şilte", defaultUnit: "M2" },

  // Cephe (Mantolama)
  { category: "Cephe (Mantolama)", name: "EPS Mantolama 3 cm", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "EPS Mantolama 5 cm", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "EPS Mantolama 8 cm", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "Karbon EPS 5 cm", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "Karbon EPS 8 cm", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "XPS Mantolama 3 cm", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "Mantolama Yapıştırıcısı", defaultUnit: "TORBA" },
  { category: "Cephe (Mantolama)", name: "Sıva Filesi", defaultUnit: "M2" },
  { category: "Cephe (Mantolama)", name: "Köşe Profili Filetli", defaultUnit: "MT" },
  { category: "Cephe (Mantolama)", name: "Damla Profili", defaultUnit: "MT" },
  { category: "Cephe (Mantolama)", name: "Mantolama Dübeli", defaultUnit: "ADET" },
  { category: "Cephe (Mantolama)", name: "Akrilik Cephe Sıvası", defaultUnit: "KG" },
  { category: "Cephe (Mantolama)", name: "Mineral Cephe Sıvası", defaultUnit: "KG" },
  { category: "Cephe (Mantolama)", name: "Cephe Astarı", defaultUnit: "LT" },

  // Hırdavat
  { category: "Hırdavat", name: "Çivi 4", defaultUnit: "KG" },
  { category: "Hırdavat", name: "Çivi 6", defaultUnit: "KG" },
  { category: "Hırdavat", name: "Çivi 8", defaultUnit: "KG" },
  { category: "Hırdavat", name: "Çivi 10", defaultUnit: "KG" },
  { category: "Hırdavat", name: "Sunta Vidası", defaultUnit: "KUTU" },
  { category: "Hırdavat", name: "Matkap Ucu", defaultUnit: "ADET" },
  { category: "Hırdavat", name: "Dübel 6 mm", defaultUnit: "KUTU" },
  { category: "Hırdavat", name: "Dübel 8 mm", defaultUnit: "KUTU" },
  { category: "Hırdavat", name: "Dübel 10 mm", defaultUnit: "KUTU" },
  { category: "Hırdavat", name: "Çelik Dübel", defaultUnit: "ADET" },
  { category: "Hırdavat", name: "Silikon (Şeffaf)", defaultUnit: "ADET" },
  { category: "Hırdavat", name: "Silikon (Beyaz)", defaultUnit: "ADET" },
  { category: "Hırdavat", name: "Polyurethane Köpük", defaultUnit: "ADET" },
  { category: "Hırdavat", name: "Yapıştırıcı (Sıvı)", defaultUnit: "KG" },
  { category: "Hırdavat", name: "Maskeleme Bandı", defaultUnit: "RULO" },
  { category: "Hırdavat", name: "İzolasyon Bandı", defaultUnit: "RULO" },
];

export function findMaterialByName(name: string): ConstructionMaterial | undefined {
  if (!name) return undefined;
  const norm = name.trim().toLowerCase();
  return CONSTRUCTION_MATERIALS.find((m) => m.name.toLowerCase() === norm);
}
