import 'package:flutter/material.dart';

import 'app_radii.dart';
import 'app_typography.dart';
import 'theme_colors.dart';

/// RN `constants/colors.ts` — 12 tema, birebir hex değerler.
abstract final class AppThemes {
  static const defaultThemeId = 'klasik';

  static final ThemeColors klasik = ThemeColors.fromHex(
    text: '#1a1a2e',
    tint: '#e85d04',
    background: '#f5f5f5',
    foreground: '#1a1a2e',
    card: '#ffffff',
    cardForeground: '#1a1a2e',
    primary: '#e85d04',
    primaryForeground: '#ffffff',
    secondary: '#16213e',
    secondaryForeground: '#ffffff',
    muted: '#eaeaea',
    mutedForeground: '#6b7280',
    accent: '#fde68a',
    accentForeground: '#92400e',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    success: '#16a34a',
    successForeground: '#ffffff',
    warning: '#d97706',
    warningForeground: '#ffffff',
    border: '#e5e7eb',
    input: '#e5e7eb',
    orange: '#e85d04',
    navy: '#16213e',
    darkNavy: '#0f3460',
  );

  static final ThemeColors lacivertPro = ThemeColors.fromHex(
    text: '#0f1e3d',
    tint: '#ff7a18',
    background: '#ffffff',
    foreground: '#0f1e3d',
    card: '#ffffff',
    cardForeground: '#0f1e3d',
    primary: '#16213e',
    primaryForeground: '#ffffff',
    secondary: '#ff7a18',
    secondaryForeground: '#ffffff',
    muted: '#f1f4fb',
    mutedForeground: '#5b6b8a',
    accent: '#ffe9d3',
    accentForeground: '#9a3a00',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    success: '#16a34a',
    successForeground: '#ffffff',
    warning: '#d97706',
    warningForeground: '#ffffff',
    border: '#dde3f0',
    input: '#dde3f0',
    orange: '#ff7a18',
    navy: '#16213e',
    darkNavy: '#0a1430',
  );

  static final ThemeColors turuncuEnerji = ThemeColors.fromHex(
    text: '#1a1a2e',
    tint: '#ff6a00',
    background: '#fff8f1',
    foreground: '#1a1a2e',
    card: '#ffffff',
    cardForeground: '#1a1a2e',
    primary: '#ff6a00',
    primaryForeground: '#ffffff',
    secondary: '#16213e',
    secondaryForeground: '#ffffff',
    muted: '#ffe8d6',
    mutedForeground: '#7a4a1f',
    accent: '#ffd6a8',
    accentForeground: '#7a3000',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    success: '#16a34a',
    successForeground: '#ffffff',
    warning: '#b45309',
    warningForeground: '#ffffff',
    border: '#ffd6a8',
    input: '#ffd6a8',
    orange: '#ff6a00',
    navy: '#16213e',
    darkNavy: '#0f3460',
  );

  static final ThemeColors beyazMinimal = ThemeColors.fromHex(
    text: '#0b1020',
    tint: '#e85d04',
    background: '#ffffff',
    foreground: '#0b1020',
    card: '#ffffff',
    cardForeground: '#0b1020',
    primary: '#16213e',
    primaryForeground: '#ffffff',
    secondary: '#0b1020',
    secondaryForeground: '#ffffff',
    muted: '#f7f7fa',
    mutedForeground: '#64748b',
    accent: '#e85d04',
    accentForeground: '#ffffff',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#d97706',
    warningForeground: '#ffffff',
    border: '#e6e8ee',
    input: '#e6e8ee',
    orange: '#e85d04',
    navy: '#16213e',
    darkNavy: '#0b1020',
  );

  static final ThemeColors gece = ThemeColors.fromHex(
    text: '#e8ecf5',
    tint: '#ff8a3c',
    background: '#0b1428',
    foreground: '#e8ecf5',
    card: '#142042',
    cardForeground: '#e8ecf5',
    primary: '#ff8a3c',
    primaryForeground: '#0b1428',
    secondary: '#1e2d56',
    secondaryForeground: '#e8ecf5',
    muted: '#1a2547',
    mutedForeground: '#9aa6c2',
    accent: '#ffb27a',
    accentForeground: '#0b1428',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#22c55e',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#0b1428',
    border: '#22305a',
    input: '#22305a',
    orange: '#ff8a3c',
    navy: '#16213e',
    darkNavy: '#0b1428',
  );

  static final ThemeColors kremSicak = ThemeColors.fromHex(
    text: '#1a1a2e',
    tint: '#d2691e',
    background: '#fbf6ee',
    foreground: '#1a1a2e',
    card: '#ffffff',
    cardForeground: '#1a1a2e',
    primary: '#d2691e',
    primaryForeground: '#ffffff',
    secondary: '#16213e',
    secondaryForeground: '#ffffff',
    muted: '#f1e8d4',
    mutedForeground: '#6b5d3f',
    accent: '#f7d8a8',
    accentForeground: '#7a3000',
    destructive: '#b91c1c',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#b45309',
    warningForeground: '#ffffff',
    border: '#ead9b8',
    input: '#ead9b8',
    orange: '#d2691e',
    navy: '#16213e',
    darkNavy: '#0f3460',
  );

  static final ThemeColors hivis = ThemeColors.fromHex(
    text: '#1c1917',
    tint: '#facc15',
    background: '#fef3c7',
    foreground: '#1c1917',
    card: '#facc15',
    cardForeground: '#1c1917',
    primary: '#1c1917',
    primaryForeground: '#facc15',
    secondary: '#1c1917',
    secondaryForeground: '#facc15',
    muted: '#fde68a',
    mutedForeground: '#57534e',
    accent: '#facc15',
    accentForeground: '#1c1917',
    destructive: '#b91c1c',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#b45309',
    warningForeground: '#ffffff',
    border: '#1c1917',
    input: '#fde68a',
    orange: '#f59e0b',
    navy: '#1c1917',
    darkNavy: '#0c0a09',
  );

  static final ThemeColors hivisOrange = ThemeColors.fromHex(
    text: '#14110f',
    tint: '#ff6b00',
    background: '#fff1e6',
    foreground: '#14110f',
    card: '#ff6b00',
    cardForeground: '#14110f',
    primary: '#14110f',
    primaryForeground: '#ff6b00',
    secondary: '#14110f',
    secondaryForeground: '#ff6b00',
    muted: '#ffd8b5',
    mutedForeground: '#5c4030',
    accent: '#ff8500',
    accentForeground: '#14110f',
    destructive: '#b91c1c',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#c2410c',
    warningForeground: '#ffffff',
    border: '#14110f',
    input: '#ffd8b5',
    orange: '#ff6b00',
    navy: '#14110f',
    darkNavy: '#0a0908',
  );

  static final ThemeColors hivisLime = ThemeColors.fromHex(
    text: '#0f140a',
    tint: '#a3e635',
    background: '#ecfccb',
    foreground: '#0f140a',
    card: '#a3e635',
    cardForeground: '#0f140a',
    primary: '#0f140a',
    primaryForeground: '#a3e635',
    secondary: '#0f140a',
    secondaryForeground: '#a3e635',
    muted: '#d9f99d',
    mutedForeground: '#3f4a2e',
    accent: '#84cc16',
    accentForeground: '#0f140a',
    destructive: '#b91c1c',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#ca8a04',
    warningForeground: '#0f140a',
    border: '#0f140a',
    input: '#d9f99d',
    orange: '#84cc16',
    navy: '#0f140a',
    darkNavy: '#050704',
  );

  static final ThemeColors steel = ThemeColors.fromHex(
    text: '#e2e8f0',
    tint: '#f59e0b',
    background: '#0f172a',
    foreground: '#e2e8f0',
    card: '#1e293b',
    cardForeground: '#e2e8f0',
    primary: '#f59e0b',
    primaryForeground: '#0f172a',
    secondary: '#1e293b',
    secondaryForeground: '#e2e8f0',
    muted: '#1e293b',
    mutedForeground: '#94a3b8',
    accent: '#0ea5e9',
    accentForeground: '#0f172a',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#10b981',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#0f172a',
    border: '#334155',
    input: '#334155',
    orange: '#f59e0b',
    navy: '#0f172a',
    darkNavy: '#020617',
  );

  static final ThemeColors steelCopper = ThemeColors.fromHex(
    text: '#f5e6d8',
    tint: '#e07a3a',
    background: '#1a1410',
    foreground: '#f5e6d8',
    card: '#2a211c',
    cardForeground: '#f5e6d8',
    primary: '#e07a3a',
    primaryForeground: '#1a1410',
    secondary: '#2a211c',
    secondaryForeground: '#f5e6d8',
    muted: '#2a211c',
    mutedForeground: '#b8a090',
    accent: '#38bdf8',
    accentForeground: '#1a1410',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#34d399',
    successForeground: '#ffffff',
    warning: '#e07a3a',
    warningForeground: '#1a1410',
    border: '#4a3a30',
    input: '#4a3a30',
    orange: '#e07a3a',
    navy: '#1a1410',
    darkNavy: '#0d0a08',
  );

  static final ThemeColors steelBlueprint = ThemeColors.fromHex(
    text: '#dbeafe',
    tint: '#22d3ee',
    background: '#071525',
    foreground: '#dbeafe',
    card: '#0f2740',
    cardForeground: '#dbeafe',
    primary: '#22d3ee',
    primaryForeground: '#071525',
    secondary: '#0f2740',
    secondaryForeground: '#dbeafe',
    muted: '#0f2740',
    mutedForeground: '#7dd3fc',
    accent: '#38bdf8',
    accentForeground: '#071525',
    destructive: '#f87171',
    destructiveForeground: '#ffffff',
    success: '#34d399',
    successForeground: '#ffffff',
    warning: '#fbbf24',
    warningForeground: '#071525',
    border: '#1e3a5f',
    input: '#1e3a5f',
    orange: '#22d3ee',
    navy: '#071525',
    darkNavy: '#030b14',
  );

  static final List<ThemeDefinition> themes = [
    ThemeDefinition(
      id: 'klasik',
      name: 'Klasik',
      description: 'Açık gri zemin, turuncu vurgu',
      isDark: false,
      preview: ThemePreview(
        bg: klasik.background,
        primary: klasik.primary,
        secondary: klasik.secondary,
      ),
      colors: klasik,
    ),
    ThemeDefinition(
      id: 'lacivert-pro',
      name: 'Lacivert Pro',
      description: 'Lacivert ağırlıklı kurumsal',
      isDark: false,
      preview: ThemePreview(
        bg: lacivertPro.background,
        primary: lacivertPro.primary,
        secondary: lacivertPro.secondary,
      ),
      colors: lacivertPro,
    ),
    ThemeDefinition(
      id: 'turuncu-enerji',
      name: 'Turuncu Enerji',
      description: 'Sıcak turuncu zemin, dinamik',
      isDark: false,
      preview: ThemePreview(
        bg: turuncuEnerji.background,
        primary: turuncuEnerji.primary,
        secondary: turuncuEnerji.secondary,
      ),
      colors: turuncuEnerji,
    ),
    ThemeDefinition(
      id: 'beyaz-minimal',
      name: 'Beyaz Minimal',
      description: 'Temiz beyaz, ince çizgiler',
      isDark: false,
      preview: ThemePreview(
        bg: beyazMinimal.background,
        primary: beyazMinimal.primary,
        secondary: beyazMinimal.secondary,
      ),
      colors: beyazMinimal,
    ),
    ThemeDefinition(
      id: 'gece',
      name: 'Gece',
      description: 'Koyu lacivert, gözleri yormaz',
      isDark: true,
      preview: ThemePreview(
        bg: gece.background,
        primary: gece.primary,
        secondary: gece.secondary,
      ),
      colors: gece,
    ),
    ThemeDefinition(
      id: 'krem-sicak',
      name: 'Krem & Sıcak',
      description: 'Yumuşak krem zemin',
      isDark: false,
      preview: ThemePreview(
        bg: kremSicak.background,
        primary: kremSicak.primary,
        secondary: kremSicak.secondary,
      ),
      colors: kremSicak,
    ),
    ThemeDefinition(
      id: 'hivis',
      name: 'Hi-Vis İSG',
      description: 'Sarı/siyah iş güvenliği modu',
      isDark: false,
      layout: ThemeLayout.hivis,
      preview: ThemePreview(
        bg: hivis.background,
        primary: hivis.primary,
        secondary: hivis.card,
      ),
      colors: hivis,
    ),
    ThemeDefinition(
      id: 'hivis-orange',
      name: 'Turuncu İSG',
      description: 'Turuncu/siyah şantiye bariyer dili',
      isDark: false,
      layout: ThemeLayout.hivis,
      preview: ThemePreview(
        bg: hivisOrange.background,
        primary: hivisOrange.primary,
        secondary: hivisOrange.card,
      ),
      colors: hivisOrange,
    ),
    ThemeDefinition(
      id: 'hivis-lime',
      name: 'Lime İSG',
      description: 'Lime yeşil yüksek görünürlük',
      isDark: false,
      layout: ThemeLayout.hivis,
      preview: ThemePreview(
        bg: hivisLime.background,
        primary: hivisLime.primary,
        secondary: hivisLime.card,
      ),
      colors: hivisLime,
    ),
    ThemeDefinition(
      id: 'steel',
      name: 'Steel & Concrete',
      description: 'Koyu lacivert, renkli kart şeritleri',
      isDark: true,
      layout: ThemeLayout.steel,
      preview: ThemePreview(
        bg: steel.background,
        primary: steel.primary,
        secondary: steel.secondary,
      ),
      colors: steel,
    ),
    ThemeDefinition(
      id: 'steel-copper',
      name: 'Bakır & Beton',
      description: 'Koyu beton, bakır/pas şeritler',
      isDark: true,
      layout: ThemeLayout.steel,
      preview: ThemePreview(
        bg: steelCopper.background,
        primary: steelCopper.primary,
        secondary: steelCopper.secondary,
      ),
      colors: steelCopper,
    ),
    ThemeDefinition(
      id: 'steel-blueprint',
      name: 'Blueprint',
      description: 'Çizim masası mavisi, siyan vurgu',
      isDark: true,
      layout: ThemeLayout.steel,
      preview: ThemePreview(
        bg: steelBlueprint.background,
        primary: steelBlueprint.primary,
        secondary: steelBlueprint.secondary,
      ),
      colors: steelBlueprint,
    ),
  ];

  static ThemeDefinition getTheme(String? id) {
    return themes.firstWhere(
      (t) => t.id == id,
      orElse: () => themes.first,
    );
  }

  /// [ThemeColors] üzerinden dinamik Material [ThemeData].
  static ThemeData buildThemeData(ThemeDefinition def) {
    final c = def.colors;
    final brightness = def.isDark ? Brightness.dark : Brightness.light;
    final base = def.isDark ? ThemeData.dark() : ThemeData.light();
    final scheme = ColorScheme(
      brightness: brightness,
      primary: c.primary,
      onPrimary: c.primaryForeground,
      secondary: c.secondary,
      onSecondary: c.secondaryForeground,
      error: c.destructive,
      onError: c.destructiveForeground,
      surface: c.card,
      onSurface: c.cardForeground,
    );

    return base.copyWith(
      colorScheme: scheme,
      scaffoldBackgroundColor: c.background,
      primaryColor: c.primary,
      dividerColor: c.border,
      cardColor: c.card,
      appBarTheme: AppBarTheme(
        backgroundColor: c.navy,
        foregroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        titleTextStyle: AppTypography.headlineMedium.copyWith(
          color: Colors.white,
          fontFamily: AppTypography.inter,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: c.primary,
        foregroundColor: c.primaryForeground,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: c.primary,
          foregroundColor: c.primaryForeground,
          shape: const RoundedRectangleBorder(borderRadius: AppRadii.md),
          textStyle: AppTypography.labelLarge.copyWith(
            color: c.primaryForeground,
            fontWeight: FontWeight.w600,
          ),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: c.card,
        border: OutlineInputBorder(
          borderRadius: AppRadii.md,
          borderSide: BorderSide(color: c.input),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: AppRadii.md,
          borderSide: BorderSide(color: c.input),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: AppRadii.md,
          borderSide: BorderSide(color: c.primary, width: 1.5),
        ),
        hintStyle: AppTypography.bodyMedium.copyWith(color: c.mutedForeground),
      ),
      textTheme: TextTheme(
        displayLarge: AppTypography.displayLarge.copyWith(color: c.foreground),
        displayMedium:
            AppTypography.displayMedium.copyWith(color: c.foreground),
        displaySmall: AppTypography.displaySmall.copyWith(color: c.foreground),
        headlineMedium:
            AppTypography.headlineMedium.copyWith(color: c.foreground),
        titleMedium: AppTypography.titleMedium.copyWith(color: c.foreground),
        bodyLarge: AppTypography.bodyLarge.copyWith(color: c.text),
        bodyMedium: AppTypography.bodyMedium.copyWith(color: c.text),
        bodySmall:
            AppTypography.bodySmall.copyWith(color: c.mutedForeground),
        labelLarge: AppTypography.labelLarge.copyWith(color: c.foreground),
      ),
    );
  }
}
